### ISSUE TITLE
Handle bitflags

### ISSUE THREAD

**Issue by eqrion** [eqrion/cbindgen#100]
It would be nice to be able to use [`bitflags!`](https://github.com/rust-lang-nursery/bitflags) and have nice output generated. Ideally the output of macro expansion would just naturally work.

Currently the output of a `bitflags!` macro is a struct containing an integer, some trait implementations, and an inherent impl that contains the associated constants for each constant from the `bitflags!` macro.

I believe if we were to parse associated constants and some more trait implementations, the expanded output would work. The associated constants part is a little tricky because the constants are rust structs initializers and not integer literals.

Alternatively, we could parse the `bitflags!` macro and output some specially crafted output. This may be easier, but I'm not sure yet.

**Comment by IGI-111** [comment]
I can confirm the expanded output does work outside of the associated constants. For instance, with macro expansion enabled, this

```rust
bitflags! {
    #[repr(C)]
    pub struct Flags: u32 {
        const A = 0b00000001;
    }
}

#[no_mangle]
pub extern "C" fn call_flag(value: &Flags) -> u32 {
    value.bits
}
```
will properly become this
```c
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

typedef struct {
  uint32_t bits;
} Flags;

uint32_t call_flag(const Flags *value);
```

**Comment by grovesNL** [comment]
This would be useful to us too. Is there a known workaround at the moment, or should we wait on #170?
