### ISSUE TITLE
Why this when we have bindgen?

### ISSUE THREAD

**Issue by alexreg** [eqrion/cbindgen#101]
I was just curious why this more recent library exists when the well-established *bindgen* crate already exists, and seems to be actively maintained?

**Comment by eqrion** [comment]
@alexreg They work in opposite directions.

`bindgen` creates a rust file that allows you to use a C/C++ library from a rust library. While `cbindgen` creates a C/C++ header that allows you to use a rust library from a C/C++ library.

Hope that clears things up!

**Comment by alexreg** [comment]
Oops, my bad! I clearly read the project descriptions too quickly. Thanks for setting things straight.
