### ISSUE TITLE
A way to specify an opaque type

### ISSUE THREAD

**Issue by compressed** [eqrion/cbindgen#104]
I'm trying to use milksnake and the binding that is generated causes some issues with python's cffi.

Here's what I have:

```rust
use std::collections::HashMap;
use std::marker::PhantomData;
use std::sync::Mutex;

#[repr(C)]
pub struct MyMap {
    map: HashMap<String, Box<String>>,
    lock: Mutex<PhantomData<()>>,
}

#[no_mangle]
pub unsafe extern "C" fn test(my_map: *const MyMap) {}
```

which generates the following `bindings.h`:

```c
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

struct HashMap_String__Box_String;
typedef struct HashMap_String__Box_String HashMap_String__Box_String;

typedef struct {
  HashMap_String__Box_String map;
  Mutex lock;
} MyMap;

void test(const MyMap *my_map);
```

However, this causes some issues with python's cffi:

```
cffi.error.CDefError: cannot parse "Mutex lock;
```

Or even if I remove the mutex:

```
TypeError: anonymous MyMap: field '$MyMap.map' is of an opaque type (not declared in cdef
```

Ideally, since these fields are private, I don't even want to expose them through the cffi. I'm not sure if this could be done automatically at part of the build or even perhaps I could pass a whitelist of types to the config. Ideally, generating `typedef ... MyMap;` would work.

**Comment by compressed** [comment]
@eqrion Ah, thanks for that! I thought I needed `#[repr(C)]` on all types that are used as arguments for the exposed functions. I didn't realize that`cbinding` would automatically figure that out and add an opaque type to the generated bindings, very cool!

Yeah I agree it could be nice to have a warning about it when it occurs or have the opaque fallback.

**Comment by jprider63** [comment]
I'm interested in this functionality as well. I have the following type declared in a separate crate: 

```
#[derive(Eq,PartialEq,Debug)]
pub enum PublicKey {
    AAEd25519 ([u8; ed25519::PUBLICKEYLENGTH])
}
```

`cbindgen` generates the following in the header: 

    typedef uint8_t PublicKey[PUBLIC_KEY_LEN];

This is problematic since `PUBLIC_KEY_LEN` isn't defined. I also might add other constructors in the future, so I want to keep the FFI interface opaque and consistent. For now, I've been manually changing the definition to:

    typedef struct PublicKey PublicKey;

**Comment by dbrgn** [comment]
You could also create non-instantiable enums: https://stackoverflow.com/questions/38315383/whats-the-rust-idiom-to-define-a-field-pointing-to-a-c-opaque-pointer

```rust
#[no_mangle]
pub enum foo_t {}
#[no_mangle]
pub enum bar_t {}

#[no_mangle]
pub fn new_foo() -> *mut foo_t {
    ...
}

#[no_mangle]
pub fn free_foo(arg: *mut foo_t) {
    ...
}
```

Of course this requires pointer casting inside the Rust FFI functions. But it makes for nicer headerfiles.

**Comment by eqrion** [comment]
I'm going to close this now as it's not clear what is actionable here. Feel free to open a new issue.
