### ISSUE TITLE
Observe '#[cfg(target_os = "linux")]' attributes

### ISSUE THREAD

**Issue by hmvp** [eqrion/cbindgen#105]
I have a function the has `#[cfg(target_os = "linux")]` However when building with a windows target the function still shows up in the header.

I expect the generated header to not contain the function. The generated docs leave them out..

**Comment by eqrion** [comment]
So `cbindgen` will generate a header that is usable for any platform. It doesn't have any knowledge of what platform it is on when it is generating a header.

If you are using a `cbindgen.toml`, try adding a:
```toml
[defines]
"target_os = linux" = "YOUR_PREPROCESSOR_DEFINE"
```
And `cbindgen` will wrap anything with `target_os = "linux"` in an `#ifdef YOUR_PREPROCESSOR_DEFINE`.

If you are using a `build.rs` with `Builder`, then unfortunately it doesn't have an option for that yet. I'll add one now.

**Comment by eqrion** [comment]
This was added for builder in `0.3.3`.

**Comment by regexident** [comment]
This issue can be closed now, I think?

**Comment by eqrion** [comment]
Yes, I believe so to.
