### ISSUE TITLE
Force export of structs.

### ISSUE THREAD

**Issue by Fulkerson** [eqrion/cbindgen#107]
Hi!

I am writing a C library in rust that is returning glib `GList *`s and `GHashTable *`s containing pointers to `#[repr(C)] pub struct A` implemented in rust. I.e. if this was rust there would be functions returning `GList<A>` and `GHashTable<A>` but since C has no concept of generics they are simply represented as `GList *`

This works pretty well except that bindings for A is never generated. If I implement a dummy `fn a() -> A` it is generated. I don't want to do this and would prefer to be able to specify in cbindgen.toml what types should be generated.

**Comment by eqrion** [comment]
I added this as
```toml
[export]
include = ["Foo"]
```
In cbindgen `0.4.0`. It can also be used with `Builder`. Feel free to open if this doesn't work for you.
