### ISSUE TITLE
Specify custom `"include <xxx.h>`

### ISSUE THREAD

**Issue by Fulkerson** [eqrion/cbindgen#108]
Hi!

I am writing a C library in rust that are returning glib `GList *`s and `GHashTable *`s.

The problem is all glib types are defined in `glib.h` so I need the generated bindings to have `#include <glib.h>` somewhere.  I don't want to put it in header because that will be placed outside of the include guards and looks really weird.

I use the glib_sys crate in rust to get access to the types. But if I let cbindgen parse that it will generate types that redefine the ones defined in `glib.h`

**Comment by eqrion** [comment]
I added this as,
```toml
includes = ["user_lib.h"]
sys_includes = ["math.h"]
```
In version `0.4.0`. Feel free to reopen this if that isn't quite right.
