### ISSUE TITLE
bindgen::cargo::Cargo::find_crate_src seemingly missing 'dylib' library type

### ISSUE THREAD

**Issue by 56quarters** [eqrion/cbindgen#109]
Hi,

Due to not reading the Cargo docs closely enough, I [attempted](https://github.com/56quarters/memento/commit/fd89aa031d82dc5e45f329796e4bcb1ea02e9bcd) to use `cbindgen` to generate a header file for a Rust library of type `dylib` as opposed to `cdylib`.

It seems like every [other type](http://doc.crates.io/manifest.html#building-dynamic-or-static-libraries)  of library is searched for by [cbindgen](https://github.com/eqrion/cbindgen/blob/bcd532f674e929b01060eec5dea72df87ac31a31/src/bindgen/cargo/cargo.rs#L173)  *except* `dylib`. Is this an oversight or an explicit choice?

In either case, does it seem reasonable to include an indication that only specific types of libraries are searched for in the [error message](https://github.com/eqrion/cbindgen/blob/bcd532f674e929b01060eec5dea72df87ac31a31/src/bindgen/parser.rs#L147) emitted? Something like...

```rust
warn!(
    "Parsing crate `{}`: can't find lib.rs of the required library type with `cargo metadata`.",
    pkg.name
);
```

Thanks!

**Comment by eqrion** [comment]
I believe ignoring `dylib` is just an oversight. I mostly just added new crate targets to that code as people complained, and didn't do it systematically. In `0.4.0` it will search for them.

I think we don't need the error message if we're now searching through all the possible library types?

**Comment by 56quarters** [comment]
Sounds good, thanks!
