### ISSUE TITLE
Pointers to pointers don't work

### ISSUE THREAD

**Issue by michaeleiselsc** [eqrion/cbindgen#114]
When I have a pointer to a pointer, e.g. `*mut *mut MyStruct m`, it gets written out in the header as `MyStruct *m` instead of `MyStruct **m`

**Comment by eqrion** [comment]
Thanks for the report. What version of `cbindgen` are you using?

When I test:
```rust
#[repr(C)]
pub struct Foo {
    a: i32,
}

pub struct Bar {
    a: i32,
}

#[no_mangle]
pub extern "C" fn root(
    a: *mut *mut i32,
    b: *mut *mut Foo,
    c: *mut *mut Bar,
) {
}
```

I get:
```cpp
#include <cstdint>
#include <cstdlib>

struct Bar;

struct Foo {
  int32_t a;
};

extern "C" {

void root(int32_t **a, Foo **b, Bar **c);

} // extern "C"
```
Which seems correct to me.

**Comment by michaeleiselsc** [comment]
hmm yeah i can't repro it either actually, feel free to close
