### ISSUE TITLE
cbindgen won't parse latest webrender

### ISSUE THREAD

**Issue by staktrace** [eqrion/cbindgen#116]
In particular webrender now does stuff like [1] which cbindgen (or syn 0.11.11) doesn't parse. I tried updating cbindgen to syn 0.12 but there's API changes that produced reams and reams of compiler errors so I assume this is nontrivial to do.

[1] https://github.com/servo/webrender/blob/9cad76acef7c1da00ba4beb1e01e764eee8fe4d5/webrender/src/renderer.rs#L2301

**Comment by staktrace** [comment]
Also note that @kvark has a PR with a workaround in servo/webrender#2316 so for testing/fixing this issue you'll need to make you use a WR version without that.

**Comment by eqrion** [comment]
It doesn't look like upgrading to syn 0.12 will fix this. See also dtolnay/syn#334.

**Comment by dtolnay** [comment]
Should work as of syn 0.12.7.

**Comment by staktrace** [comment]
This happened again with the following lines of code:

https://github.com/servo/webrender/blob/b6e69a8efbcd8dc3e0c0a8a9925e6a9355635de3/webrender/src/capture.rs#L28
https://github.com/servo/webrender/blob/b6e69a8efbcd8dc3e0c0a8a9925e6a9355635de3/webrender/src/renderer.rs#L2321
https://github.com/servo/webrender/blob/b6e69a8efbcd8dc3e0c0a8a9925e6a9355635de3/webrender/src/renderer.rs#L2323

**Comment by kvark** [comment]
I thought this is fixed as of 11 days ago? Maybe we need to update `syn` dependency?

**Comment by staktrace** [comment]
Yeah but updating to the latest `syn` is not trivial due to API changes.

**Comment by eqrion** [comment]
I've updated master to `syn 12.10.0`, I'll wait to push a release for a bit, but for now this should be fixed.
