### ISSUE TITLE
Maintain a more stable ordering of types

### ISSUE THREAD

**Issue by jrmuizel** [eqrion/cbindgen#12]
Anecdotally, it seems like if you change when I a type gets used it can end up changing order in the generated header which causes needless code churn. It might be nice to avoid this somehow.

**Comment by staktrace** [comment]
This is actually quite annoying for when my WR update cron job, resulting in frequent merge conflicts. Is there something we can do to make the ordering stable? The SideOffsets2D_f32 keeps flip-flopping win the u32 variant.

**Comment by eqrion** [comment]
There are definitely improvements we can make for the ordering. Unfortunately I haven't had time to improve cbindgen recently.

The issue with SideOffsets2D_f32 and SideOffsets2D_u32 seems like it could be from some uses of HashMap, which is non deterministic across changes.

I pushed a new release that uses BTreeMap instead, which might help your case. Let me know if it's still bad.

**Comment by staktrace** [comment]
Initial results look good. Thanks! I'm ok with closing this issue for now and reopening it later if it's still a problem.

**Comment by eqrion** [comment]
Okay cool. Let's keep this issue open for now, there are some other changes I'd like to make in the future.

**Comment by eqrion** [comment]
I'm going to close this now as I think we do okay here. If there's something specific that comes up, lets open a new issue.
