### ISSUE TITLE
The bonus tag accessor for repr(u8) should be wrapped in a struct

### ISSUE THREAD

**Issue by Gankro** [eqrion/cbindgen#122]
Very strictly speaking it's only valid to access a prefix, and bare `Tag` isn't a prefix of `{ Tag; ... }`. But `{ Tag; }` is.

**Comment by RReverser** [comment]
Just for the record: as far as I understand, C is still fine and this wrapping is needed just for C++.

**Comment by Gankro** [comment]
yes.

(relevant cpp spec)

![32247217-063aafd8-be58-11e7-8b9d-67dca2e633cb](https://user-images.githubusercontent.com/1136864/35537964-38b5a8ba-051a-11e8-8c44-08fb42cc35f7.png)
