### ISSUE TITLE
ParseSyntaxError when lifetime is the first in a list of trait bounds

### ISSUE THREAD

**Issue by adeschamps** [eqrion/cbindgen#124]
The following causes a `ParseSyntaxError`. If the lifetime parameter is not the first in the list, then it works fine.

```rust
use std::fmt::Debug;

struct FailsToParse<'a> {
    item: Box<'a + Debug>,
}

struct WorksFine<'a> {
    item: Box<Debug + 'a>,
}
```

**Comment by adeschamps** [comment]
The error originates in `syn`. The latest version of appears to parse this code just fine, but `cbindgen` doesn't compile if I update `syn` from `0.11` to `0.12`.

**Comment by eqrion** [comment]
Okay, thanks for testing this! I'm currently working on updating to the latest syn so that should fix this.

-------- Original Message --------

**Comment by eqrion** [comment]
I believe this was fixed awhile ago when we updated to a newer syn. Feel free to reopen if it's still an issue.
