### ISSUE TITLE
Handling of Constants

### ISSUE THREAD

**Issue by dbrgn** [eqrion/cbindgen#129]
Is there a clean way to handle constants (e.g. log levels)?

I could create an enum:

```rust
#[no_mangle]
#[repr(u8)]
pub enum my_log_level_t {
    LEVEL_TRACE = 0,
    LEVEL_DEBUG = 1,
    LEVEL_INFO = 2,
    LEVEL_WARN = 3,
    LEVEL_ERROR = 4,
    LEVEL_OFF = 5,
}

#[no_mangle]
pub extern "C" fn my_log_init(level: my_log_level_t) -> bool {
    ...
}
```

However, this way C code could still pass in for example the value `6`, which results in undefined behavior and a crash. So I'd prefer to work with plain u8 constants.

But this does not end up in the generated header file:

```rust
pub const LEVEL_TRACE: uint8_t = 0;
```

Would it be an option to convert `pub const` types to `#define`s?

**Comment by eqrion** [comment]
Hmm, we should be emitting `#define`s for `const`, see this [test](https://github.com/eqrion/cbindgen/blob/master/tests/rust/constant.rs) and [expectation](https://github.com/eqrion/cbindgen/blob/master/tests/expectations/constant.c). Where are you defining the `const`?

If you are generating bindings with the `cbindgen` binary, does asking for verbose output give some information?

**Comment by dbrgn** [comment]
Ah:

> WARN: Skip my-ffi::LEVEL_TRACE - (Cannot have a non primitive const definition.)

As mentioned above, the definition is `pub const LEVEL_TRACE: uint8_t = 0`. It works with a plain `u8`.

I also get a few warnings like this one:

```
WARN: Can't find uint8_t. This usually means that this type was incompatible or not found.
WARN: Can't find uint32_t. This usually means that this type was incompatible or not found.
```

...so I tried this in the config file:

```
[parse]
parse_deps = true
include = ["libc"]
```

...but that didn't help.

Should type aliases (like `uint8_t`) be supported?

**Comment by eqrion** [comment]
> Should type aliases (like uint8_t) be supported?

Yes we actually do support some type aliases from [libc](https://github.com/eqrion/cbindgen/blob/9abaf017c01fb7c40e0c98cd11aaf2e8d9746d82/src/bindgen/ir/ty.rs#L66) (hardcoded because handling general exports, imports, renames, type aliases is difficult). I just missed the type aliases in `libc` that don't start with `c_`. So I'd be fine with adding those to the list of primitive types.

**Comment by dbrgn** [comment]
Thanks, I'll send a pull request.
