### ISSUE TITLE
Be more careful with floating point type sizes

### ISSUE THREAD

**Issue by eqrion** [eqrion/cbindgen#13]
Currently `f32` and `f64` are assumed to be `float` and `double` respectively and this isn't guaranteed to be true to my knowledge.

**Comment by jrmuizel** [comment]
It's true that float and double are not guaranteed to be a particular size but I don't think there's much that we can do about that. C doesn't have fixed size floating point types.

**Comment by rlhunt** [comment]
Yeah I agree. Best solution I can think of is to add a `static_assert(sizeof(float) == 4)` etc, and an option to disable converting f32 to float.

I'll just leave this issue for anyone wondering about this behavior.
