### ISSUE TITLE
Provide hooks for alternate language generators

### ISSUE THREAD

**Issue by Michael-F-Bryan** [eqrion/cbindgen#134]
Are there any plans to allow people to create their own binding generators? I'm currently working with some legacy Delphi code and it'd be really nice if I could use `cbindgen` to analyse a crate and then make bindings using the results.

In my particular example I've created a class which loads a DLL at runtime (using `LoadLibrary`/`dlopen`)  and calling a function from the DLL is done via the class. I'm manually maintaining the bindings for now, but I've already had several issues due to out-of-sync bindings so it'd be nice to automate this stuff.

From what I can tell this could be possible if `Bindings`' internals were public, although making them public means it's harder to change internals, doesn't it?

<details>
<summary>Example of current bindings</summary>

```delphi
unit bindings;

interface

uses Windows,
  System.Classes,
  System.SysUtils;

type

  EDllLoadError = class(Exception);

  TBindings = class
  private
    handle: NativeUint;

  public
    add: Function(Integer; Integer): Integer;
    last_error_message: Function: PChar;

    constructor Create(lib: String);
    destructor Destroy; override;
  end;

implementation

constructor TBindings.Create(lib: String);
begin
  if not FileExists(lib) then
    raise EDllLoadError.Create(lib + ' doesn''t exist');
  handle := LoadLibrary(PWideChar(lib));
  if handle = 0 then
    raise EDllLoadError.Create('Unable to load ' + lib);

  @add := GetProcAddress(handle, PWideChar('add'));
  if @add = nil then
    raise EDllLoadError.Create('Couldn''t find the "add" function');
  @last_error_message := GetProcAddress(handle, PWideChar('last_error_message'));
  if @last_error_message = nil then
    raise EDllLoadError.Create('Couldn''t find the "last_error_message" function');

end;

destructor TBindings.Destroy;
begin
  if handle <> 0 then
    FreeLibrary(handle);

  inherited;
end;

end.
```
</details>

**Comment by Dushistov** [comment]
@Michael-F-Bryan You can try different approach that implementing in my crate:

https://github.com/Dushistov/rust_swig

instead of implicity share all `extern "C"`, it explicity share what you describe,
plus it generates also binding on target language. At now it has c++ and java support,
and generates `rust extern "C"` functions plus java and c++ classes to call this `extern "C"` code and hide details from user. If you write Object Pascal/Deplhi backend it will be automaticaly generate `TBindings`

**Comment by Michael-F-Bryan** [comment]
> it explicity share what you describe,

That's one of the things I want to avoid though. If I have to write a bunch of `foreigner_class!()` declarations and update them every time the rest of my code changes, then I'm not actually gaining much over my current setup (other than the code needing to be kept in sync is Rust instead of Delphi).

`cbindgen` actually does exactly what I want, namely I can define a strict interface that my DLL exposes (as a bunch of `extern "C"` functions), then `cbindgen` is able to scan through the crate and figure out what code is necessary to use it from C/C++. I just want to be able to generate a Delphi header file equivalent as well.

**Comment by eqrion** [comment]
Hmm, I have not put much thought into this. I think this would be an admirable goal, but it could be a lot of work to develop and maintain. Currently the internals (`Bindings, Library`) make assumptions for C/C++ (and there's already some code complexity from having two different languages there).

I don't know how close `Delhi` bindings are to C/C++, so I don't have a good feel for the work.

There are a lot of things common between binding generators here, so maybe factoring parts of cbindgen into different crates could make this easier?

For example, a large part of cbindgen is mimicking cargo/rustc with syn to get all the types defined in a crate and it's dependencies. That could be factored out into a `syn-expand` crate which could do that work portably.

Additionally, functions that operate on the expanded crate could be added to that crate or another such as gathering all `extern "C"` functions, gathering dependencies of types, and expanding macro_rules.

I think with those two things, cbindgen would be more or less just a pretty printer as the IR could probably be mostly eliminated/replaced with Syn, which would make writing a Delhi version much simpler.

**Comment by Dushistov** [comment]
@eqrion 

>For example, a large part of cbindgen is mimicking cargo/rustc with syn to get all the types defined in a crate and it's dependencies. 

That would be great get such functionality for my crate.

**Comment by eqrion** [comment]
I'm going to close this for now as this is beyond the scope of this project and what I have time to do.
