### ISSUE TITLE
cbindgen 0.4.x dependency breaks builds since 0.4.4 release

### ISSUE THREAD

**Issue by WrinklyNinja** [eqrion/cbindgen#136]
I've got a dependency on cbindgen 0.4.3 in my library's Cargo.toml, and if I try building it on stable Rust without a lockfile present (e.g. on CI, if I'm a new user of my library), Cargo will download the 0.4.4 release as it's supposed to be compatible, but then the build fails because 0.4.4 seems to have introduced a nightly requirement.

**Comment by eqrion** [comment]
Ah yes, 0.4.4 did introduce a nightly requirement. That’s a backwards incompatible change so I should’ve done a breaking change. I’ll see if I can yank that version and add a 0.5.0.

**Comment by WrinklyNinja** [comment]
May I ask why the nightly requirement has been introduced, and what I'll lose out by sticking to 0.4.3? cbindgen is a very useful tool, but I'm not going to pin a requirement on nightly on my builds (and downstream builds) because it's just not dependable.

**Comment by eqrion** [comment]
The nightly requirement was added from a workaround to get cbindgen binaries working outside of cargo after the upgrade of ‘syn’ which added a dependency on ‘proc_macro’.

The update of syn mostly added better error messages and better parsing. The nightly requirement should hopefully be temporary once we find a better solution.

**Comment by WrinklyNinja** [comment]
Thanks for the explanation, and I'm sure yanking 0.4.4 and re-releasing it as 0.5.0 would be a big help to not just me but all your non-nightly users.

**Comment by eqrion** [comment]
I just did the yank and re-release as 0.5.0. I'll close this for now as this is fixed.
