### ISSUE TITLE
Generate header for public functions exposed via `pub use`

### ISSUE THREAD

**Issue by michaeleiselsc** [eqrion/cbindgen#139]
I have a parent crate that makes the functions of its dependencies public via `pub use`, but unfortunately cbindgen doesn't generate a header for them. How might I fix this? FYI, my current design is that this parent is just a wrapper around all of the crates that my C project actually depends on, so that I won't duplicate code between the exported libs and instead just have one big lib

**Comment by zbraniecki** [comment]
Is there any workaround for this except of declaring my own local struct and wrapping the `pub use` one?

**Comment by emilio** [comment]
#362 should allow exporting functions of dependent crates, let me know if that doesn't work by any chance.

For regular types, you shouldn't need anything else than telling cbindgen to parse your dependencies via `parse_deps`.
