### ISSUE TITLE
Document the dependency on nightly

### ISSUE THREAD

**Issue by Michael-F-Bryan** [eqrion/cbindgen#146]
I just upgraded to `0.5.0` and found that `cbindgen` no longer compiles on `stable`, which is a pain because I'm running it as part of a build script. Would you be able to note on the README that `nightly` is required?

**Comment by eqrion** [comment]
`cbindgen` should no longer depend on `nightly` in `0.5.1` which I just released, so we shouldn't need any documentation. This will hopefully not happen again.

**Comment by eqrion** [comment]
Well turns out the fix is only working when built locally, but the linking error is back when used through `cargo install`. I've yanked `0.5.1` for now, I'll add a note that `nightly` is still required.
