### ISSUE TITLE
Using cbindgen and parse-expand inside of buildscript creates infinite rustc process tree

### ISSUE THREAD

**Issue by untitaker** [eqrion/cbindgen#153]
Steps to reproduce:

* Clone & compile https://github.com/untitaker/cbindgen-recursion
* Watch in e.g. htop how process tree explodes:

![lol](https://user-images.githubusercontent.com/837573/37375059-48903a90-271e-11e8-994f-eadbebfdb273.png)

**Comment by untitaker** [comment]
Duplicate of https://github.com/eqrion/cbindgen/issues/72... I suppose if I set the env variable there the problem vanishes. Still I think cbindgen should be able to stop the recursion by itself.

**Comment by vmx** [comment]
This works on master. Probably fixed by https://github.com/eqrion/cbindgen/pull/371. Thanks @untitaker for providing an easy to reproduce example, so that it can quickly be checked if things are fixed.

This issue can be closed.
