### ISSUE TITLE
Allow not writing the header if it hasn't changed

### ISSUE THREAD

**Issue by hfiguiere** [eqrion/cbindgen#155]
Currently cbindgen is responsible of most of the time spent compiling my project.

One of the reasons is that it rewrites the `.h` even though it hasn't changed. And that forces a rebuild of the C++ code. Even though I have ccache it is still taking some time.

One way could be that `Bindings::write_to_file()` compare the output and not overwrite the file if there is no change.

**Comment by eqrion** [comment]
I changed `Bindings::write_to_file` to compare the output before writing in cce8c416f7acd661b2f733ae8728c720265638ae. That should hopefully resolve this.

It changes the method signature to return whether the file was written to or not, so technically it's a breaking change and will need a version bump. Right now I'm waiting a bit to collect changes before doing that. I'll resolve this when I publish the change.

**Comment by eqrion** [comment]
This was published in `0.6.0`
