### ISSUE TITLE
Parsing failure with !allow(unused_variables)

### ISSUE THREAD

**Issue by staktrace** [eqrion/cbindgen#169]
The line at https://github.com/servo/webrender/blob/78d6e6c6362ec78e863b1254be71a70c8682fb14/webrender/src/device.rs#L606 was added recently to webrender in servo/webrender#2764 and causes cbindgen to fail during the parsing step. The error message is also not particularly useful:

```
ERROR: Parsing crate `webrender`:``:
ParseError(Some("failed to parse crate: failed to parse all tokens"))
```

**Comment by emilio** [comment]
Huh, that's invalid rust, isn't it? That's a global attribute, I'm ~sure it shouldn't be allowed in that position and the right thing to do is `#[allow(..)]`, not `#![allow(..)]`.

**Comment by emilio** [comment]
I mean, I guess if it passed CI is valid, but I wouldn't have expected that at all.

**Comment by staktrace** [comment]
Changing it to `#[allow(..)]` does let cbindgen parse it successfully. Maybe we should just make that change in webrender?

**Comment by emilio** [comment]
https://github.com/servo/webrender/pull/2781

**Comment by eqrion** [comment]
e36f1854ca7700c59fcdfc8243013ddb9d98c566 updated syn to `0.14.1` which should resolve this issue. I will close this when I publish a new cbindgen version. 

In the meantime using master will workaround this.

**Comment by eqrion** [comment]
cbindgen version `0.6.1` should include this fix.
