### ISSUE TITLE
cbindgen 0.6.1 produces incorrect constants

### ISSUE THREAD

**Issue by crusty-dave** [eqrion/cbindgen#198]
The following:
`    pub const COOKIE_ID_LEN: usize = 10;
`

produces the following:
`static const uintptr_t COOKIE_ID_LEN = 10;
`

I believe that it should produce the following:
`static const size_t COOKIE_ID_LEN = 10;
`

**Comment by emilio** [comment]
Rust's `usize` is defined to be closer to `uintptr_t`, I think.

**Comment by eqrion** [comment]
Here's a relevant part of the [rust specification](https://doc.rust-lang.org/reference/types.html#machine-types).

> Machine-dependent integer types
>
> The usize type is an unsigned integer type with the same number of bits as the platform's pointer type. It can represent every memory address in the process.

So I think I'll close this as correct behavior. But I'm not a compiler/standards guru so let me know if it's more complicated.
