### ISSUE TITLE
extern crate required with edition 2018

### ISSUE THREAD

**Issue by mcgoo** [eqrion/cbindgen#221]
I am using Rust 1.30 beta. I created a couple of crates with edition 2018. One has the C interface I am trying to export, which depends on and needs to export some types from the other crate. The top level crate needs to say `extern crate child_crate;`  (otherwise optional in 2018 edition) in order for `cbindgen` to find and export the types it contains. 

I had tried the following config, but it did not work until I added the `extern crate` line.

```
[parse]
parse_deps = true
include = ["child_crate"]
```

**Comment by eqrion** [comment]
This is an issue with the current design of cbindgen (as a parser). This would be solved by #214.

**Comment by emilio** [comment]
I think this in particular was fixed by #332
