### ISSUE TITLE
Prefix for associated constants

### ISSUE THREAD

**Issue by kvark** [eqrion/cbindgen#232]
We are looking at the bitflags output of this struct:
```rust
bitflags! {
    #[repr(transparent)]
    pub struct TextureUsageFlags: u32 {
        const TRANSFER_SRC = 1;
        const TRANSFER_DST = 2;
        const SAMPLED = 4;
        const STORAGE = 8;
        const OUTPUT_ATTACHMENT = 16;
        const PRESENT = 32;
        const NONE = 0;
        const WRITE_ALL = 2 + 8 + 16;
    }
}
```
The result looks like this:
```cpp
#define WGPUOUTPUT_ATTACHMENT (TextureUsageFlags){ .bits = 16 }
#define WGPUPRESENT (TextureUsageFlags){ .bits = 32 }
```
There is "WGPU" prefix attached (which we specify in the options, but it's only means for types), and instead we'd want the type name to be the prefix, i.e.
```cpp
WGPUTextureUsageFlags_OUTPUT_ATTACHMENT
```
The current output is not very usable - it's not desired to have the type prefix affecting associated constants, and the way they are generated now there appears to be conflict between types (i.e. we have similar constants for `BufferUsageFlags` bitflags, and they overlap).

cc @grovesNL @eqrion @IGI-111

**Comment by IGI-111** [comment]
Ah yes, that is one of the caveats, no explicit namespacing.

It should be relatively simple to add some (like a type prefix as you mention), but we should probably discuss the edge cases and document the specifics, because it's necessarily `cbindgen` specific behavior.

**Comment by kvark** [comment]
Do you have any concerns (edge cases) in mind?

**Comment by IGI-111** [comment]
Mostly collisions. Between namespaces and types, between classic constants and associated variable constants and so on.
`#define` collisions are especially hairy to debug so I'm inclined to be careful. But perhaps I'm just overthinking this.

I'm certainly not opposed to just doing the least surprising behavior by default, i.e.: just adding a type prefix. But we can probably avoid some pains with an optional prefix for typenames for instance. Something like

```toml
type_prefix = "__" # "" by default
```
That'd make `WGPU__TextureUsageFlags_OUTPUT_ATTACHMENT` rather than `WGPUTextureUsageFlags_OUTPUT_ATTACHMENT` in case you have some weirdly named types that overlap constants.

**Comment by kvark** [comment]
Thing is, the current code already produces `#define` collisions on a much more frequent basis (since the constants don't get prefixed by the owner type names). And I don't think we should have `__` as a separate prefix - I would prefer the type name to match with the constant prefix exactly, which makes the search easier. If we wanted `WGPU__`, we could specify this as an original type prefix.

**Comment by IGI-111** [comment]
Verbose mode also indicates the constants generated as INFO which is quite neat. But I think when there is an explicit constant conflict we should WARN.

**Comment by kvark** [comment]
I believe the probability of a Rust program defining `Foo_BAR` is extremely low, since it's not even complying with the default naming convention. Thus, we should be safe assuming `Foo_BAR` is the designated reflection of `Foo::BAR` constant, and signal otherwise.

Speaking of signalling, I think a collision should be `error!`, not `warn!`. Having stuff colliding more often than not would mean a problem for any user of the C header.

**Comment by IGI-111** [comment]
That's correct. If the standard is followed even acronym types should be CamelCase.

I guess it still leaves single character types and anyone who doesn't follow the naming convention, but point taken those are super rare cases.

Oh and I agree, collisions in this case should be errors. 

I'll try to follow this up with a PR tomorrow, the changes should be relatively straightforward.

**Comment by kvark** [comment]
Awesome, thank you!!!

**Comment by IGI-111** [comment]
I suppose this ought to be closed now @kvark, I guess the autoclosing didn't work when Github was having hiccups.

**Comment by kvark** [comment]
@eqrion when is this going to be published?
