### ISSUE TITLE
Associated constants don't take the prefix into account properly

### ISSUE THREAD

**Issue by kvark** [eqrion/cbindgen#238]
#234 is missing a test for preffixed bindings. This is what we get:
```cpp
typedef uint32_t WGPUTextureUsageFlags;
#define WGPUTextureUsageFlags_TRANSFER_DST (TextureUsageFlags){ .bits = 2 }
```
This doesn't compile, clearly, since there is no `TextureUsageFlags`.

cc @IGI-111

**Comment by IGI-111** [comment]
I'm taking a look at this, will have to possibly add an alternative to LiteralExpr so that the prefixing can take place.

**Comment by kvark** [comment]
Thank you @IGI-111 !
I tried to test this today and faced other issues.
First of all, the `#[repr(transparent)]` isn't taken into account here, since the macro tries to assign the `.bits` field, and there are no fields on `uint32_t`.

Secondly, something strange is going on when I run wgpu-bindings:
```
kvark@ant /mnt/base/moz/wgpu $ cargo +nightly run --manifest-path wgpu-bindings/Cargo.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s                                                                                                               
     Running `target/debug/wgpu-bindings`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CargoExpand("wgpu-native", Compile("    Finished dev [unoptimized + debuginfo] target(s) in 0.07s\n"))', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
It looks like the compilation is successful, but something returns an error?

**Comment by IGI-111** [comment]
Supporting `#repr(transparent)` should be pretty straightforward since the we're only interested in the first field.

No idea about that error message though, which unwrap is failing here?

**Comment by kvark** [comment]
It's the `unwrap` from this code on our side:
```rust
    cbindgen::Builder::new()
        .with_crate(source_dir)
        .with_config(config)
        .with_parse_expand(&["wgpu-native"])
        .generate()
        .unwrap()
        .write_to_file(crate_dir.join("wgpu.h"));
```

**Comment by IGI-111** [comment]
That is quite a weird `Err` value indeed. I bet something just fails silently inside and the output is just misleading because it's missing a proper error message.

**Comment by IGI-111** [comment]
I'd start by figuring out where that Err is generated, and then finding the source of the failure, it's probably wise to pull out gdb here.

Maybe run cbindgen on only part of the offending codebase, or on all files individually? I mean with a relatively minimal example we could start to speculate on the cause.

Best you can do is open an issue with the smallest offending code you can find.
