### ISSUE TITLE
export.prefix doesn't rename functions

### ISSUE THREAD

**Issue by dignifiedquire** [eqrion/cbindgen#259]
I have a config

```toml
[export]
prefix = "PGP_"
```

and a declaration in my code like this

```rust
#[no_mangle]
pub extern "C" fn key_from_armor(raw: *const u8, len: libc::size_t) -> *mut PublicOrSecret {
 // ...
}
```

which results in 

```c
PGP_PublicOrSecret *key_from_armor(const uint8_t *raw, size_t len);
```

but I would have expected 

```c
PGP_PublicOrSecret *PGP_key_from_armor(const uint8_t *raw, size_t len);
```

is this is not supported, and if so, is there a way to achieve this? 

- cbindgen 0.6.7

**Comment by eqrion** [comment]
This is not supported, as the name of `extern "C" fn` is linker visible. Adding a prefix to it would break this and you will get link errors.

Structs, fields, enums, and function arguments are not visible to the linker so we can rename them as we want.
