### ISSUE TITLE
`repr(int)` enums are currently broken

### ISSUE THREAD

**Issue by petertodd** [eqrion/cbindgen#261]
See https://github.com/rust-lang/rust/pull/56619

Here's an example, `lib.rs`:

```
#![allow(dead_code)]

#[repr(u8)]
pub enum Foo {
    A { 
        a: u16,
        b: u8, 
    },  
    B,  
}

extern "C" {
    fn foo() -> Foo;
}
```

`Foo` is actually laid out as:

```
$ cargo rustc -- -Z print-type-sizes
   Compiling foo v0.1.0 (/tmp/foo)
print-type-size type: `Foo`: 4 bytes, alignment: 2 bytes
print-type-size     discriminant: 1 bytes
print-type-size     variant `A`: 3 bytes
print-type-size         field `.b`: 1 bytes
print-type-size         field `.a`: 2 bytes
print-type-size     variant `B`: 0 bytes
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
```

...with `b` and `a` of the `A` variant reversed. Meanwhile `cbindgen` happily produces a binding with those fields in the wrong order:

```
$ cbindgen foo
#include <cstdint>
#include <cstdlib>

union Foo {
  enum class Tag : uint8_t {
    A,
    B,
  };

  struct A_Body {
    Tag tag;
    uint16_t a;
    uint8_t b;
  };

  struct {
    Tag tag;
  };
  A_Body a;
};

extern "C" {

extern Foo foo();

} // extern "C"
```

A decent temporary fix would be to temporarily disable `repr(int)` enums with variants containing multiple fields of different types until `rustc` fixes this;  if every field is the same type the ordering isn't changed. Similarly single-field variants are also fine because they can't be reordered.

**Comment by petertodd** [comment]
FWIW, this was working in `nightly-2017-04-12-x86_64-unknown-linux-gnu` and broke in `nightly-2017-04-13-x86_64-unknown-linux-gnu`

The commit that broke it is almost certainly https://github.com/rust-lang/rust/commit/4f6f4eb7c386b01dec8c0337a600365407ba6a56, which re-enabled field reordering.

**Comment by emilio** [comment]
Assuming https://github.com/rust-lang/rust/pull/56887 is the right fix (which I suspect it is, but I'm not a rustc developer) I'd prefer to keep this for now and try to uplift that patch instead in rust stable / beta instead of disabling them on cbindgen.

**Comment by eqrion** [comment]
So just to clarify, is this is an issue with rustc reordering fields when it shouldn't or in cbindgen misunderstanding `#[repr(c)]`?

**Comment by petertodd** [comment]
Update: https://github.com/rust-lang/rust/pull/56887 got merged so this will be working again in newer compilers.
