### ISSUE TITLE
cbindgen can't parse some macro expanded code from rustc

### ISSUE THREAD

**Issue by jrmuizel** [eqrion/cbindgen#268]
When running master cbindgen to generate the webrender bindings I get:
```
ERROR: Parsing crate `euclid`:``:
Error { start_span: Span, end_span: Span, message: "expected one of: `_`, `box`, `-`, literal, parentheses, `&`, square brackets" }
ERROR: Couldn't generate bindings for toolkit/library/rust/.
```

reverting the syn update doesn't seem to help

**Comment by jrmuizel** [comment]
I expect this might have to do with version of nightly rust used for macro expansion.

**Comment by jrmuizel** [comment]
I'm running rustc 1.33.0-nightly (9eac38634 2018-12-31)

**Comment by jrmuizel** [comment]
This still fails for me with cbindgen v0.6.7 and rustc 1.33.0-nightly (f381a9625 2019-01-04)

**Comment by kvark** [comment]
Doesn't work for me with rustc 1.33.0-nightly (d22fa2d87 2019-01-08) and cbindgen 0.6.8

**Comment by jrmuizel** [comment]
```
rustup run nightly-2018-12-15 cbindgen toolkit/library/rust/ --lockfile Cargo.lock --crate webrender_bindings -o gfx/webrender_bindings/webrender_ffi_generated.h
```
also works

**Comment by emilio** [comment]
This will get fixed by https://github.com/servo/euclid/pull/314, which would avoid the macro expansion and such.

**Comment by lu-zero** [comment]
I can confirm it happens on https://github.com/lu-zero/crav1e as well.

**Comment by TomzBench** [comment]
I get `error parsing crate` when i have `parse.expanded` set for my crate.

Is it possible to generate bindings for macro expanded code?

**Comment by emilio** [comment]
Yeah, this is expected unless you use `expanded`, but then it should work. Let's close and open new issues for concrete/actionable bugs. Thanks.
