### ISSUE TITLE
Should respect #[export_name]

### ISSUE THREAD

**Issue by RReverser** [eqrion/cbindgen#283]
Rust supports `#[export_name = "..."]` as an alternative to `#[no_mangle]` that allows to customise exported name of various items.

**Comment by nxrighthere** [comment]
Any progress on this? 🙏

**Comment by emilio** [comment]
This shouldn't be hard to fix, on functions at least. `src/bindgen/parser.rs` should be tweaked to look at this attribute on top of `no_mangle` (grep for `is_no_mangle`), and tweak the `Path` to be the value of the attribute rather than the function name if it's present.

**Comment by alaroldai** [comment]
I can take a look at this if nobody's started on it yet.

**Comment by nxrighthere** [comment]
That would be nice. I haven't started and just using a simple workaround for now...

**Comment by nxrighthere** [comment]
Hey, thanks! @alaroldai
