### ISSUE TITLE
Special-case the bitflags! macro

### ISSUE THREAD

**Issue by bholley** [eqrion/cbindgen#284]
cbindgen now has support for associated constants, but getting that for bitflags! requires macro expansion, which in turn requires nightly Rust. This means we can't use it in Firefox.

As a result, we have to duplicate various lists of bit values, which is error-prone. I think it would be worthwhile to handle bitflags as a special case to auto-generate what we manually do for FontInstanceFlags [1].

CC @emilio @eqrion 

[1] https://searchfox.org/mozilla-central/rev/6c784c93cfbd5119ed07773a170b59fbce1377ea/gfx/webrender_bindings/webrender_ffi.h#99

**Comment by jrmuizel** [comment]
@kvark wanted this for https://github.com/gfx-rs/wgpu as well. I agree that special casing the macro is the right approach.

**Comment by emilio** [comment]
#293 has a patch for this. I want to use this for the style system too. Ideally with the C++17 inline consts, but we'll see about that.
