### ISSUE TITLE
What Changed?

### ISSUE THREAD

**Issue by bdubbs** [eqrion/cbindgen#297]
When I download the latest tarball via wget, there is no NEWS, Release Notes, or Changelog.  Searching the github pages, there does not seem to be anything similar.

Please include a NEWS file in release tarballs describing the significant changes in a new release.

**Comment by emilio** [comment]
All the release tags' commits (like https://github.com/eqrion/cbindgen/commit/5ec5a82d268c8fe907767394ee7ad15718f3f09d) contain the relevant information.

Adding it to more places would be a bit of a burden...

**Comment by bdubbs** [comment]
Many of our users only download the tarball from a url we provide with a program like wget.

Take a look at http://oss-watch.ac.uk/resources/releasemanagementbestpractice, especially the section with the title RELEASE-NOTES and CHANGES.  Traditionally the file that accomplished that goal is named NEWS and has a list of significant changes, latest on top.  

Not all users want to navigate to github for every package.  

How much of a burden is it to paste a list of changes into a single file.  A minute or two for each release?

Bruce Dubbs
linuxfromscratch.org

**Comment by emilio** [comment]
How does a file with only the latest version changes help when you update more than one version at a time? I guess a changelog of some sort does make sense though.

**Comment by eqrion** [comment]
I've added a CHANGES file with the notes for previous releases based on commit history. I'll try to keep that up to date.

**Comment by bdubbs** [comment]
Thank you.
