### ISSUE TITLE
Can't run tests locally, '-std=c++11' required

### ISSUE THREAD

**Issue by RazrFalcon** [eqrion/cbindgen#30]
On GCC 5.4.0 tests doesn't compile without `-std=c++11`.

**Comment by rlhunt** [comment]
Ah, I'm running with a newer GCC and I updated travis to use a newer one. I'll try and specify the flag in the test script. You can run tests with `./run-tests.py -c` and it will test the C output which should be fine.

**Comment by eqrion** [comment]
Fixed by 77d3664c013
