### ISSUE TITLE
Configure comment style, or suppress the `*` per line.

### ISSUE THREAD

**Issue by ralfbiedert** [eqrion/cbindgen#302]
For `C` projects, documentation is currently generated like this:

```
  /**
   * Result of f() 
   */
  my_ray combined;
```

In our project we feed the generated header into other tools, which then generate HTML. However, the `*` each line mess up the output format and require manual cleanup each time we regenerate. 

It would be nice to configure the comment style, e.g., being able to select:

- The current style
- `//` each line
- Only a `/*` at the start and an `*/` in the end.

**Comment by eqrion** [comment]
@emilio Can this be closed now?

**Comment by emilio** [comment]
Yes. Fixed by #305.
