### ISSUE TITLE
Cbindgen generates incomplete types

### ISSUE THREAD

**Issue by playXE** [eqrion/cbindgen#310]
For example:
```rust
struct Assembler {
       pub data: Vec<u8>
}
```
From this I get:
```cpp
template <typename T>
struct Vec;

struct Assembler
{
  Vec<uint8_t> data;
};
```
And `Vec` in C++ is incomplete when compiling using Clang or GCC. 

## How to fix?
Just changing from `struct Vec` to `struct Vec {}` But that thing doesn't allow manipulations on the vector. 
Another way is generate this definition:
```cpp
template <typename T>
struct Vec {
      T* buf;
      size_t cap;
      size_t len;
}
```

**Comment by emilio** [comment]
That'd be unsound, the layout of `Vec` is not guaranteed by `rustc`.

**Comment by eqrion** [comment]
Yes, the layout of std::Vec is [unspecified](https://doc.rust-lang.org/std/vec/struct.Vec.html#guarantees). You can probably work around this by taking ownership of the contents of the Vec, and moving them to a wrapper struct which you provide to the users of your API.

**Comment by xajik** [comment]
Hi, 
Is there any workaround to this? I particularly have an issue with a struct that contains many vectors with struct and visitors inside, wrapping each in wrapper creates so much boilerplate code...

**Comment by emilio** [comment]
You can pass a pointer to the struct just fine, or you can have a generic wrapper type like `OwnedSlice` here: https://crisal.io/words/2020/02/28/C++-rust-ffi-patterns-1-complex-data-structures.html
