### ISSUE TITLE
Single-quote chars are wrapped incorrectly

### ISSUE THREAD

**Issue by RReverser** [eqrion/cbindgen#320]
Just something I've noticed while looking at the code of #318 and confirmed by manual tests: trying to export a single quote char results in invalid output:

Rust:
```rust
pub const QUOTE: char = '\'';
```

C:
```c
#define QUOTE '''
```

C++
```cpp
static const wchar_t QUOTE = ''';
```

Unfortunately, noticed this only after the PR was merged, so raising as a separate tracking issue.

cc @AxelNennker

**Comment by RReverser** [comment]
Same probably applies to other special chars like `\n` expanded into a newline. Worth extending tests to include various cases and use something like [`char::escape_default`](https://doc.rust-lang.org/std/primitive.char.html#method.escape_default) to cover all of them.

**Comment by emilio** [comment]
Ah, nice catch.
