### ISSUE TITLE
unimplemented panic on "FnPtr" 

### ISSUE THREAD

**Issue by dignifiedquire** [eqrion/cbindgen#328]
I am not sure which part of my code exactly triggers this yet, but I am getting 

```
thread 'main' panicked at 'not yet implemented: FuncPtr(Primitive(Void), [(Some("_"), Primitive(SizeT)), (Some("_1"), Primitive(SizeT))])', /Users/dignifiedquire/opensource/cbindgen/src/bindgen/mangle.rs:51:37
```

when trying to generate the bindings.

**Comment by dignifiedquire** [comment]
It seems that it is an issue in handling `Option<extern "C" fn() >`

**Comment by RReverser** [comment]
@dignifiedquire Sounds like duplicate of https://github.com/eqrion/cbindgen/issues/326 (literally the last issue before yours).

**Comment by emilio** [comment]
Is there any chance you could come up with a reduced test-case?

**Comment by dignifiedquire** [comment]
I cannot reproduce it anymore, I am quite confused about it, but I might have changed sth in my code in the meantime. Will report if I can retrigger it again.
