### ISSUE TITLE
cbindgen 0.8.6 stopped producing opaque structs

### ISSUE THREAD

**Issue by lu-zero** [eqrion/cbindgen#337]
Tested with the current https://github.com/lu-zero/crav1e

All the structures in `src/lib.rs` aren't emitted anymore.

Everything works in `0.8.4`.

**Comment by lu-zero** [comment]
7efea29 is the source of the problem.

**Comment by emilio** [comment]
cc @Gankro

**Comment by emilio** [comment]
@lu-zero a minimized test-case that shows the behavior difference would be great

**Comment by Gankro** [comment]
Do you mean https://github.com/xiph/rav1e ..? (your link doesn't work for me)

**Comment by lu-zero** [comment]
sorry, I meat https://github.com/lu-zero/crav1e

**Comment by lu-zero** [comment]
@emilio let me see if I can manage to pin the problem.

**Comment by Gankro** [comment]
Running `make` locally on the current master branch for that library seems to correctly produce decls like: `typedef struct RaConfig RaConfig;` for opaque types. Is this only happening for you on a branch?

**Comment by lu-zero** [comment]
It is happening on the master branch, try to `make examples` to see the missing types or run `cbindgen` directly:

I'm seeing:
```
WARN: Can't find Context. This usually means that this type was incompatible or not found.
WARN: Can't find Context. This usually means that this type was incompatible or not found.
WARN: Can't find Context. This usually means that this type was incompatible or not found.
WARN: Can't find Frame. This usually means that this type was incompatible or not found.
WARN: Can't find Frame. This usually means that this type was incompatible or not found.
WARN: Can't find Context. This usually means that this type was incompatible or not found.
WARN: Can't find Frame. This usually means that this type was incompatible or not found.
WARN: Can't find Context. This usually means that this type was incompatible or not found.
WARN: Can't find Context. This usually means that this type was incompatible or not found.
WARN: Can't find Context. This usually means that this type was incompatible or not found.
WARN: Can't find Frame. This usually means that this type was incompatible or not found.
```

**Comment by Gankro** [comment]
Everything seems fine with a clean `make examples`, perhaps there is a platform-specific issue? I'm on macos 10.14.


Output I see:

```
crav1e::make clean
cargo clean
rm -f rav1e.pc
rm -f include/rav1e.h
rm -f simple_encoding
crav1e::cargo clean
crav1e::make examples
cargo build --release
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.34
   Compiling libc v0.2.54
   Compiling autocfg v0.1.2
   Compiling arrayvec v0.4.10
   Compiling rand_core v0.4.0
   Compiling ryu v0.2.8
   Compiling cfg-if v0.1.7
   Compiling nodrop v0.1.13
   Compiling serde v1.0.91
   Compiling lazy_static v1.3.0
   Compiling unicode-width v0.1.5
   Compiling scopeguard v0.3.3
   Compiling memoffset v0.2.1
   Compiling ansi_term v0.11.0
   Compiling byteorder v1.3.1
   Compiling bitflags v1.0.4
   Compiling rayon-core v1.4.1
   Compiling cbindgen v0.8.4
   Compiling strsim v0.8.0
   Compiling vec_map v0.8.1
   Compiling itoa v0.4.4
   Compiling remove_dir_all v0.5.1
   Compiling num-traits v0.2.6
   Compiling pkg-config v0.3.14
   Compiling rayon v1.0.3
   Compiling rustc-demangle v0.1.14
   Compiling either v1.5.2
   Compiling bitstream-io v0.8.2
   Compiling rand_core v0.3.1
   Compiling crossbeam-utils v0.2.2
   Compiling log v0.4.6
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling backtrace v0.3.15
   Compiling textwrap v0.11.0
   Compiling rand_isaac v0.1.1
   Compiling rand_xorshift v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rav1e v0.1.0 (https://github.com/xiph/rav1e#f9e05a73)
   Compiling crossbeam-epoch v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling rand_os v0.1.3
   Compiling atty v0.2.11
   Compiling num_cpus v1.10.0
   Compiling rand v0.5.6
   Compiling clap v2.33.0
   Compiling crossbeam-deque v0.2.0
   Compiling quote v0.6.12
   Compiling tempfile v3.0.7
   Compiling serde_derive v1.0.91
   Compiling proc-macro-hack v0.5.7
   Compiling arg_enum_proc_macro v0.1.1
   Compiling paste-impl v0.1.5
   Compiling paste v0.1.5
   Compiling toml v0.4.10
   Compiling serde_json v1.0.39
   Compiling bincode v1.0.1
   Compiling crav1e v0.1.0 (/Users/ABeingessner/dev/crav1e)
warning: type alias is never used: `ChromaSamplePosition`
   --> src/lib.rs:101:1
    |
101 | type ChromaSamplePosition=rav1e::ChromaSamplePosition;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(dead_code)] on by default

warning: type alias is never used: `ChromaSampling`
   --> src/lib.rs:102:1
    |
102 | type ChromaSampling=rav1e::ChromaSampling;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: type alias is never used: `Rational`
   --> src/lib.rs:106:1
    |
106 | type Rational=rav1e::Rational;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    Finished release [optimized + debuginfo] target(s) in 2m 48s
sed -e "s;@prefix@;/usr/local;" \
	    -e "s;@libdir@;/usr/local/lib;" \
	    -e "s;@incdir@;/usr/local/include;" \
            -e "s;@VERSION@;0.1.0;" \
            -e "s;@PRIVATE_LIBS@;$(rustc --print native-static-libs /dev/null --crate-type staticlib 2>&1| grep native-static-libs | cut -d ':' -f 3);" data/rav1e.pc.in > rav1e.pc
cc -g -O0 -std=c99 c-examples/simple_encoding.c -o simple_encoding -Ltarget/release/ -lrav1e `grep Libs.private rav1e.pc | cut -d ':' -f 2` -Iinclude
```

**Comment by Gankro** [comment]
Oh, I see, the tip commit is 2e86f0d304fad2b7cde58f88ebe002a8c2f626ab, "orkaround cbindgen 0.8.6". Let me just revert that locally...

**Comment by Gankro** [comment]
Ah ok got it nice and broken.

So the issue you're running into is that, as I understand it, it is basically undefined what cbindgen will do if your crate graph has two types with the same name. This is because cbindgen does not actually understand namespacing of any kind (because it would be too much work for what this project is). 

In this case Context and Frame conflict with rav1e's versions of these types, and cbindgen doesn't know what to do. You can "fix" this by renaming Context and Frame to something that doesn't conflict. I *think* the fact that we were building your bindings properly was basically a fluke. But I'll confirm that.

**Comment by lu-zero** [comment]
Ok, I guess I should put a note somewhere regarding "known pitfalls" :)

**Comment by lu-zero** [comment]
> So the issue you're running into is that, as I understand it, it is basically undefined what cbindgen will do if your crate graph has two types with the same name. This is because cbindgen does not actually understand namespacing of any kind (because it would be too much work for what this project is).

Is it possible to at least force cbindgen to give priority to the root crate when in doubt? It wouldn't be a full solution but would work for most of the use cases if not all.

**Comment by Gankro** [comment]
In this case, it would still be mess because cbindgen will basically see:

```
struct Context {
  inner: Context,
}
```

but it's possible we could support your case better by just being way more aggressive about marking a type as opaque as a fallback, even to the point of accidentally unifying unrelated types with the same name?

**Comment by lu-zero** [comment]
I'd be fine with even a mean to explicitly mark the types as exportable (and opaque)

**Comment by lu-zero** [comment]
If you could point me on where to start I can try myself if you are busy.
