### ISSUE TITLE
Using --target <arch> make the testsuite fails

### ISSUE THREAD

**Issue by sylvestre** [eqrion/cbindgen#342]
`$ cargo test  --target x86_64-unknown-linux-gnu  --verbose`

cbindgen expects the binary in 
`build/cbindgen/target/debug/cbindgen`
when --target installed cbindgen to:
`target/x86_64-unknown-linux-gnu/debug/cbindgen`

```
---- test_annotation stdout ----
Running: "/home/sylvestre/dev/debian/debcargo-conf/build/cbindgen/target/debug/cbindgen" "--lang" "c" "--style" "type" "-o" "/home/sylvestre/dev/debian/debcargo-conf/build/cbindgen/tests/expectations/annotation.c" "/home/sylvestre/dev/debian/debcargo-conf/build/cbindgen/tests/rust/annotation.rs"
thread 'test_annotation' panicked at 'failed to execute process: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5

```

**Comment by sylvestre** [comment]
@emilio can you please help with this? thanks

**Comment by emilio** [comment]
https://github.com/eqrion/cbindgen/pull/348, but if you want to spend some time to switch our tests to use the library version of cbindgen instead it'd be greatly appreciated, I didn't look into it but should be fairly easy.
