### ISSUE TITLE
cbindgen panic: "unable to find generic path"

### ISSUE THREAD

**Issue by Tzeroxik** [eqrion/cbindgen#350]
Hi, I'm wrapping a specific part of Arrayfire, and when generating it panicked with this error
```
ERROR: Cannot find a mangling for generic path GenericPath { path: Path { name: "Complex" }, export_name: "Complex", generics: [Primitive(Float)], ctype: None }. This usually means that a type referenced by this generic was incompatible or not found.
```
I think it'the problem is Array<T>'s generics, the problem is I need to somehow wrap the array and expose the resource to C, so it's not dropped.

My repo is [this](https://github.com/fica-ps/fica
)  if it helps 

And I generated using: `cbindgen -o .\include\fica.h -l C`

**Comment by emilio** [comment]
Do you know of a way to repro? I tried to use that crate like `$ cbindgen -o include/c/fica.h -l C` and it worked, but I assume that it is because you worked around it somehow. Also which cbindgen version did you try?

**Comment by Tzeroxik** [comment]
It kinda works? like it does generate the ffi headers, but give's me that error, I've always kept it updated and been using it frequently, so the latest, doesn't really generate the Array ffi if I put it on a struct, 'do I worked around by using a void ptr instead.

**Comment by emilio** [comment]
Ah, this is working as expected.

This is not a panic, just an error meaning that `cbindgen` doesn't know about `Complex<f32>` / `Complex<f64>`, these are defined in a different crate (`num-complex`) which isn't parsed since it's not specified in `parse.include`.

Adding `num-complex` to the `include` list of dependencies gets rid of this error.

**Comment by Tzeroxik** [comment]
Oh I had for some reason to delete "parse_deps=true", save it and then change the file, but then it worked, thanks!
