### ISSUE TITLE
Consider providing binary file for releases

### ISSUE THREAD

**Issue by upsuper** [eqrion/cbindgen#351]
People may want to run cbindgen on CI, and it doesn't always make sense to build the whole cbindgen from scratch on CI.

It would be very helpful if there can be pre-built binaries for common platforms (especially Linux x64) that CI scripts would be able to just download and execute.

**Comment by emilio** [comment]
Do you know of a good way to do that? Is there any way to configure Travis to provide it somehow?

**Comment by upsuper** [comment]
Travis CI provides this natively, see: [GitHub Releases Uploading](https://docs.travis-ci.com/user/deployment/releases/). It can be configured to be triggered when a new version is tagged.

Rust projects like ripgrep has [relied on this for long](https://github.com/BurntSushi/ripgrep/blob/392682d35296bda5c0d0cccf43bae55be3d084df/.travis.yml#L90-L100). Although I haven't released binary release of Rust projects, my experience with releasing static content generated from [areweasyncyet.rs](https://github.com/rustasync/areweasyncyet.rs/blob/93c6b95a971655502ee781ee329f41929a100981/.travis.yml#L17-L22) gives me an impression that it's quite easy to do as far as your build process already produced the right file.

**Comment by upsuper** [comment]
Basically you just need to generate a personal token and put it encrypted in Travis CI, and have the deployment setup, then it happens automatically.

**Comment by emilio** [comment]
Let me know if it doesn't work by any chance :)

**Comment by upsuper** [comment]
Thanks! I'll try it out and report back :)
