### ISSUE TITLE
Add a feature to simplify enums used as tagged unions

### ISSUE THREAD

**Issue by porky11** [eqrion/cbindgen#353]
When enum variants contain data, they will be converted to a tagged union in C.
The variants will be converted to new types with complicated long names.

In cases, where the enum variants only contain a single field, it seems preferable not to define new types for the fields of the untagged union in the C struct, representing the tagged union, but just use the single field types.

An example, where this causes unnecessary structs, is [wgpu](https://github.com/gfx-rs/wgpu).
I just described in [this issue](https://github.com/gfx-rs/wgpu/issues/219), how I'd prefer the C code to look like.

Since I don't see a reason to have single value wrapper structs in a C binding, I'd prefer it to just use the existing types by default in this case.
But I can also think of configuration options for enums.
For consistency reasons it may be more reasonable to always create a new type, except the specific option is set.

**Comment by emilio** [comment]
ABI of structs may be different, so not 100% sure this is fixable. Though I guess these are never passed by value. Not sure if the presence of a struct in C can change the ABI in any architecture.

C has anonymous structs which we could use too, I think.

**Comment by porky11** [comment]
Anonymous structs seem like a good idea. They could also be used in other cases, where there are multiple fields.
In order to avoid naming conflicts for anonymous structs, you would just prefix the anonymous struct field names with enum field names. But the special case, where an enum variant only has a single unnamed field, the `_0` suffix will be dropped.

Some example:

```rust
enum Test {
    Variant1(i32),
    Variant2(i32, i32),
    Variant3 { x: i32 },
    Variant4 { x: i32, y: i32 },
}
```

This will turn into following C types:

```C
typedef enum {
    Variant1,
    Variant2,
    Variant3,
    Variant4,
} Test_Tag;

typedef struct {
    Test_Tag tag;
    union {
        struct {
            int variant1;
        };
        struct {
            int variant2_0;
            int variant2_1;
        };
        struct {
            int variant3_x;
        };
        struct {
            int variant4_x;
            int variant4_y;
        };
    };
} Test;
```

Anonymous structs seem like a good idea. They could also be used in other cases, where there are multiple fields.
In order to avoid naming conflicts for anonymous structs, you would just prefix the anonymous struct field names with enum field names. But the special case, where an enum variant only has a single unnamed field, the `_0` suffix will be dropped.

Some example:

```rust
enum Test {
    Variant1(i32),
    Variant2(i32, i32),
    Variant3 { x: i32 },
    Variant4 { x: i32, y: i32 },
}
```

This will turn into following C types:

```C
typedef enum {
    Variant1,
    Variant2,
    Variant3,
    Variant4,
} Test_Tag;

typedef struct {
    Test_Tag tag;
    union {
        struct {
            int variant1;
        };
        struct {
            int variant2_0;
            int variant2_1;
        };
        struct {
            int variant3_x;
        };
        struct {
            int variant4_x;
            int variant4_y;
        };
    };
} Test;
```

I tried it and it compiles well.

The old behavior may still be useful useful in some cases, so it should be enabled by a flag.
Maybe there could even be two flags, one for variants with named fields, and one for unnamed fields.

It might be reasonable to map only structs with unnamed fields to anonymous structs by default, since something like writing `variant4.x` looks better than `variant2._1`.

**Comment by petrochenkov** [comment]
I'm working on this, https://github.com/eqrion/cbindgen/pull/627 does some preparatory refactorings.

**Comment by petrochenkov** [comment]
I experimented with this a bit and it looks like only variants with a single unnamed field would benefit from this optimization.

In this case we can collapse `variant._0` into just `variant`, but in other cases
```rust
variant_0
variant_1
variant_field
```
are not better, and maybe worse than
```rust
variant._0
variant._1
variant.field
```

Optimizing only `variant._0` also eliminates all possibilities for name conflicts (which arise when we start concatenating names) since the set of variant/field names remains the same as without the optimization.
So I'm going to implement only the "single unnamed field" case.

**Comment by petrochenkov** [comment]
Implemented in https://github.com/eqrion/cbindgen/pull/631.
