### ISSUE TITLE
Escape `Double`

### ISSUE THREAD

**Issue by zbraniecki** [eqrion/cbindgen#368]
```irc
> @emilio> gandalf: ah, `double` is a C++ keyword, use `Double_` and file a cbindgen issue to escape that?
```

**Comment by emilio** [comment]
Minimal rust file would be `#[repr(C, u8)] enum FluentValue { Double(f64), String(*const nsString) }`, or something of that sort.

**Comment by TheKK** [comment]
I'd like to help this one :)
