### ISSUE TITLE
Preserve empty lines in comments.

### ISSUE THREAD

**Issue by 0ndorio** [eqrion/cbindgen#369]
I just updated an older project and realized that the changes introduced in 9248f84d0cc1f87b849262638ec277e030476446 started to skip empty lines in doc comments. As we normally use them to structure longer comments into multiple sections the resulting header is now much harder to read. 

Is their any configuration I might miss to reintroduce the old behavior and preserve them?

**Comment by emilio** [comment]
I think it may have been an oversight, given no test changed to reflect that `is_empty()` check.

I think a patch that removes the `is_empty()` check and adds a test would be welcome :)
