### ISSUE TITLE
Rust char is not wchar_t e.g. on Windows

### ISSUE THREAD

**Issue by hsivonen** [eqrion/cbindgen#373]
Rust's `char` is 32 bits wide. `wchar_t` is not 32 bits wide e.g. on Windows, so mapping Rust's `char` to `wchar_t` is incorrect. (`wchar_t` is non-portable and generally a bad idea.) Rust's `char` should map to C11 `char32_t`.

**Comment by emilio** [comment]
I agree :)

Do you plan to fix this? It should be straight-forward.

**Comment by adrianwong** [comment]
We've run into this same issue, in Prince. Mind if I gave this fix a shot?

**Comment by adrianwong** [comment]
@emilio Thanks for reviewing the PR! Would it be possible to make a new release on crates.io please?

**Comment by emilio** [comment]
Yeah, I'll try to get to that. A bit swamped atm, sorry :/

**Comment by adrianwong** [comment]
Thanks Emilio, no worries.

**Comment by adrianwong** [comment]
Hi, any news on a release date please? :)

**Comment by adrianwong** [comment]
Hi, any news on a release date please? :)

**Comment by emilio** [comment]
Just published 0.10.0, sorry for the lag.

**Comment by adrianwong** [comment]
Not a problem, @emilio. Thanks for your work.
