### ISSUE TITLE
-Zunstable-options --pretty=expanded requires a nightly compiler.

### ISSUE THREAD

**Issue by jrmuizel** [eqrion/cbindgen#38]
I've filed https://github.com/rust-lang/rust/issues/43697 to find out what we should do about this.

**Comment by eqrion** [comment]
If #24 is fixed we shouldn't need macro pretty printing, but in the mean time it's only needed for some euclid types.

We could remove the macro use there if necessary, but it would add some code repetition.

**Comment by jrmuizel** [comment]
I've also filed https://github.com/dtolnay/syn/issues/191 which would let us get at a post macro_rules! ast.

**Comment by eqrion** [comment]
I'm going to close this as `--pretty=expanded` won't be stabilized and we'll need to find another solution.

**Comment by bavalpey** [comment]
I'm using cbindgen and I'm running into this issue, I believe the same cause here, where macro expansion isn't working without using +nightly (e.g. setting parse.expand)
I would like to not have to rely on nightly. Is there an alternative here? I didn't see a solution in the issue list.
