### ISSUE TITLE
Any way to accomplish conditional inclusion?

### ISSUE THREAD

**Issue by mcronce** [eqrion/cbindgen#390]
I've got a library that I'm exposing for use through FFI, which will have one of three concrete implementations (one of which will have different function signatures) depending on `features` flags.  Is there any way to get `cbindgen` to only include items that match a specific set of features?  I'm running `cbindgen` as a library from `build.rs` using `cbindgen::Builder`, if that makes a difference.

Strawman example:

`src/lib/mod.rs`
```rust
extern crate real_lib as real;

#[cfg(feature = "a")]
mod a;
#[cfg(all(feature = "b", not(feature = "a")))]
mod b;
#[cfg(all(not(feature = "a"), not(feature = "b")))]
mod c;

#[cfg(feature = "a")]
pub use a::*;
#[cfg(all(feature = "b", not(feature = "a")))]
pub use b::*;
#[cfg(all(not(feature = "a"), not(feature = "b")))]
pub use c::*;

// Empty struct to use as opaque struct, just used to get compile-time type-checking in C instead of YOLOing it with void*
#[no_mangle]
pub struct Thing;

// Not exported
fn do_something(i: i32) -> Option<()> {
    Some(())
}

#[no_mangle]
pub extern fn thing_new() -> *mut Thing {
    Box::into_raw(Box::new(real::Thing::new())) as *mut Thing
}
```

`src/lib/a.rs`
```rust
#![cfg(feature = "a")]
extern crate real_lib as real;

use crate::Thing;
use crate::check_something;

#[no_mangle]
pub extern fn thing_try_something(thing: *mut Thing, i: i32) {
    let thing = unsafe { &mut *(thing as *mut real::Thing) }; // Yes, I know
    match check_something(i) {
        Some(_) => thing.success(),
        None(_) => thing.failure()
    };
}
```

`src/lib/b.rs`
```rust
#![cfg(all(feature = "b", not(feature = "a")))]
extern crate real_lib as real;

use crate::Thing;

#[no_mangle]
pub extern fn thing_try_something(thing: *mut Thing, i: i32) {
    let thing = unsafe { &mut *(thing as *mut real::Thing) };
    thing.success(); // In this implementation, we have externally-provided guarantees that allow us to skip check_something() and allow the Thing to perform its success activities
}
```

`src/lib/c.rs`
```rust
#![cfg(all(not(feature = "a"), not(feature = "b")))]
extern crate real_lib as real;

use std::ffi::CStr;
use std::os::raw::c_char;

use crate::Thing;
use crate::check_something;

// This one, however, is weird and requires a string for whatever reason
#[no_mangle]
pub extern fn thing_try_something(thing: *mut Thing, i: *const c_char) {
    let thing = unsafe { &mut *(thing as *mut real::Thing) };
    let i_cstr = unsafe { CStr::from_ptr(i) };
    let i_str = i_cstr.to_str().expect("to_str");    
    let i_forreal = i_str.parse::<i32>().expect("parse");
    match check_something(i_forreal) {
        Some(_) => thing.success(),
        None(_) => thing.failure()
    }
}
```

What I'm looking for is for `Thing` and _one_ definition of `thing_try_something` to show up in my resulting header file, depending on the enabled features.  However, what I get right now is `Thing` and _all three_ definitions of `thing_try_something`.  Is this possible?

As a side note, I think I discovered while going through documentation that I don't need the empty structs to act as opaque structs and can skip that first type punning step in every function body, so that's a nice reduction ;)

**Comment by emilio** [comment]
I think this should work, maybe with caveats, if you use the `[defines]` section in your build.rs, see:

https://github.com/eqrion/cbindgen/blob/master/docs.md#defines-and-cfgs

Does that work? Or not? If not, what is the configuration you've been using?

Thanks!

**Comment by emilio** [comment]
Please reopen if the `[defines]` section doesn't work for you.
