### ISSUE TITLE
Include re-exported constants in output

### ISSUE THREAD

**Issue by swilcox3** [eqrion/cbindgen#392]
I've got a bunch of constants defined in one of my crates like this :
```
pub mod error_codes {
    pub const SUCCESS: i32 = 0;
    pub const DB_FILE_NOT_FOUND: i32 = 1;
    pub const DB_FILE_LOCKED: i32 = 2;
    ...
}
```
This is not in the crate I'm generating a header for, it's in a base crate lots of other code includes.  In my FFI crate I'm reexporting these error codes like this:
`pub use ps_client::error_codes::*;`

I'd like to see all those error codes show up in my generated .h, but they don't.  I've experimented with [parse] section in cbindgen.toml, but no dice.  I'm sure this is probably possible, but I'm not sure how to do it.  Do I just need to copy/paste those constants into my FFI crate?

**Comment by emilio** [comment]
`parse_deps = true` and `include = ["ps_client"]` should work. If not, could you provide concrete STR?

**Comment by swilcox3** [comment]
Here's a minimum reproducible case:
[mrc.zip](https://github.com/eqrion/cbindgen/files/3672663/mrc.zip)
Unzip, go into ffi and cargo build --release.  I expect that the constant EXPORT_ME defined in base/src/lib.rs would show up in the generated ffi/src/ffi.h.

**Comment by emilio** [comment]
Ah, so... cbindgen doesn't understand re-exports because it doesn't understand modules (see #7). 

But it _does_ support generating constants, functions, etc from dependencies, see https://github.com/eqrion/cbindgen/pull/362.

So in this case just using `extra_bindings = ["base"]` fixes it.
