### ISSUE TITLE
Cbindgen emits header file that can not be used with C

### ISSUE THREAD

**Issue by Firstyear** [eqrion/cbindgen#393]
Because cbindgen emits a header such as:

```
#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>

extern "C" {

uintptr_t do_nothing_rust();

} // extern "C"
```

This fails to compile when using C, because the 4 c++ headers can't be found:

```
In file included from /home/william/development/389ds/ds/ldap/servers/slapd/configdse.c:27:
/home/william/development/389ds/ds/ldap/servers/slapd/rust-slapi-private.h:1:10: fatal error: cstdarg: No such file or directory
    1 | #include <cstdarg>
      |          ^~~~~~~~~
```

These should be masked behind an ifdef for C++ only, so that they don't cause issues with C building. 

IE the emitted header should be:

```
#ifdef __cplusplus
#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>

extern "C" {
#endif 

uintptr_t do_nothing_rust(); 

#ifdef __cplusplus
}
#endif   
```

**Comment by Firstyear** [comment]
Should have mentioned, this is using the cbindgen::generate function from build.rs

**Comment by Firstyear** [comment]
You could possibly have the example of using builder in build.rs be `cbindgen::Builder::with_language(cbindgen::Language::C)` instead so it's obvious that you need to change the language flag for one or the other?

**Comment by emilio** [comment]
Yeah, this is totally doable, there are a bunch of language switches. So this only needs docs, right?

**Comment by Firstyear** [comment]
Probably only docs, I think that the builder::new() defaulting to C++ was a surprise, and that led to my confusion. So if the examples for using this always included with_language, that would be great.
