### ISSUE TITLE
cbindgen is verbose

### ISSUE THREAD

**Issue by NickeZ** [eqrion/cbindgen#398]
Hi,

I'm running cbindgen on my project and it emits several `WARN Skip ...`. Is there a way to silent those warnings? IMO that is more like informational level logging.

Thanks

**Comment by emilio** [comment]
`2>/dev/null` if you're running the CLI. But we could probably add a `no-verbose` or `quiet` flag or something to avoid doing this work?

https://github.com/eqrion/cbindgen/blob/087d36f32a41cb0c9a64c5395002400b93347ddc/src/main.rs#L223

**Comment by emilio** [comment]
Was fixed by #400.

**Comment by NickeZ** [comment]
I guess technically there was a fix. But no I'm afraid that I might miss real warnings when using the quiet flag. Are there any warnings that I might miss?

Another solution would be to bump the level of these warnings to info, then I could continue to print real warnings. Having something *not exported* isn't something wrong right?

**Comment by itrombley** [comment]
I agree with @NickeZ. I have functions that I don't want exported through a C ABI and they're being treated as if there's something wrong.

**Comment by emilio** [comment]
Let's open a new issue for that please?
