### ISSUE TITLE
Constant doc strings are not placed into the C header output

### ISSUE THREAD

**Issue by jamesmunns** [eqrion/cbindgen#403]
Given the following input:

```rust
/// A reasonable approximation of PI
pub const PI: f32 = 3.14159;
```

The following output is generated

```c
#define PI 3.14159
```

I would instead expect the following to be generated:

```c
/**
 * A reasonable approximation of PI
 */
#define PI 3.14159
```

So far I have successfully generated docs for other types, but constants do not seem to have their documentation brought along.

**Comment by arsing** [comment]
https://github.com/eqrion/cbindgen/pull/471

**Comment by jamesmunns** [comment]
Thank you @arsing and @emilio!
