### ISSUE TITLE
Support static link lib features for DLLs. Namely: __declspec(dll_import) and gnu equivalent.

### ISSUE THREAD

**Issue by ruffianeo** [eqrion/cbindgen#405]
Is not one of the main selling points of Rust, that there exists a smooth migration path from C/C++? One feature I cannot find after reading cbindgen docs is support for dynamic/shared library import export control. The header file generated should (optionally, when building the crate with crate_type = "dylib" or crate_type = "cdylib") support dll import adornments on exported functions, such, that all a user has to do is to link to the static link lib of the dll and include the header.

Currently:

    #[no_mangle]
    pub extern "C" fn add(x: i32, y: i32) -> i32 {
        x + y
    }
produces:

    int32_t add(int32_t x, int32_t y);

Optionally (command line or cbindgen.toml controlled) it should produce something like:

    __declspec(dllimport) int32_t add(int32_t x, int32_t y); 

on a windows system.
And (not a gcc user here.. so others will know better how it looks like on gcc systems):

    __attribute__ ((dllimport)) int32_t add(int32_t x, int32_t y);

on a gcc system. (clang identical to gcc here?!)

**Comment by emilio** [comment]
This is supported more generally via `fn.prefix` and `fn.postfix` configuration options, which IIRC can also be configured per function via `/// cbindgen:` directories. But let me know if I'm missing something here.

Thanks for filing!
