### ISSUE TITLE
Support `MaybeUninit` and `ManuallyDrop`

### ISSUE THREAD

**Issue by 42triangles** [eqrion/cbindgen#406]
I think these should really be supported, as it is can be somewhat important when dealing with a C API. Since both are `#[repr(transparent)]`, and since (afaik) C fields do not have to be initialized as long as they aren't being used, `MaybeUninit<T>` and `ManuallyDrop<T>` should probably be exopsed as whatever `T` would translated to on its own.

**Comment by emilio** [comment]
This makes sense. We already hande other standard types, so I don't think it should be too terrible to fix.

**Comment by chrysn** [comment]
Would that allow writing C functions as `pub extern "C" fn my_fun(x: &mut MaybeUninit<somestruct>)`?

I'm trying to follow along the lines of what's there for NonNull and Cell, maybe I can come up with a PR.

**Comment by emilio** [comment]
Yes it would.

**Comment by emilio** [comment]
And yeah, doing what `Cell` does sounds alright.

**Comment by cceckman** [comment]
If I'm [this comment](https://github.com/eqrion/cbindgen/pull/578#issuecomment-700648236), this is closed as of 0.15.0 (af6d2e3fbbc2121c4519fd601d7fa6b525298def in tree). @emilio / @Hywan can you confirm?

(Thanks for adding this!)

**Comment by emilio** [comment]
Yes, that's right!
