### ISSUE TITLE
Raw identifier is not generated correctly

### ISSUE THREAD

**Issue by fanzeyi** [eqrion/cbindgen#410]
The following Rust code uses [raw identifier](https://doc.rust-lang.org/stable/edition-guide/rust-2018/module-system/raw-identifiers.html), and the generated code preserved the raw identifier syntax which isn't valid syntax for C/C++:

```rust
#[no_mangle]
pub extern "C" fn r#match() {}
```

With the example [cbindgen.toml](https://raw.githubusercontent.com/eqrion/cbindgen/master/template.toml), the following C++ code is generated:

```cpp
#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>


extern "C" {

void r#match();

} // extern "C"
```

Desired output:

```cpp
#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>


extern "C" {

void match();

} // extern "C"
```

**Comment by emilio** [comment]
This should be relatively straight-forward to fix in `src/bindgen/parser.rs`.

**Comment by TheKK** [comment]
I'd like to work on this one!
