### ISSUE TITLE
Generate `#define` without `const`

### ISSUE THREAD

**Issue by rask** [eqrion/cbindgen#417]
My use-case:

I am writing a C-ABI library to be used with FFI in an interpreted language. The language requires me to have a line as follows in the generated C header:

```
#define FFI_LIB "pathtolib.so"
```

This constant has no effect on the library code itself, and exists only to satisfy the FFI consumer in the interpreted language FFI implementation.

This means I should add a `pub const FFI_LIB ...` into the Rust source, which bothers me as it adds no value there.

I can see no configuration value (or `build.rs` API) to provide `#define` values that are "just injected" into the generated bindings.

Would this be possible to add?

**Comment by rask** [comment]
It seems that I can hax a `#define` in there using `.with_header(...)` inside `build.rs`.

```rust
extern crate cbindgen;

use std::env;
use cbindgen::Language;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
      .with_crate(crate_dir)
      .with_language(Language::C)
      .with_no_includes()
      .with_header("#define FFI_LIB \"pathtolib.so\"")
      .generate()
      .expect("Unable to generate bindings")
      .write_to_file("target/debug/my_library.h");
}
```

Disgusting? Yes.

**Comment by emilio** [comment]
Yeah, [`header`](https://searchfox.org/mozilla-central/rev/cce8b90aece0f42e5025e45282de16066eeaa662/gfx/webrender_bindings/cbindgen.toml#1) is what we use for this kind of stuff, like license boilerplate and other stuff.

**Comment by emilio** [comment]
I think this is ok to inject arbitrary code. It could be cleaner if you use rust raw strings (so you don't have to escape the quotes), but otherwise I think this is not too bad? If you have a better idea for an API I'd be happy to reopening and taking a look.

**Comment by rask** [comment]
Okay, this works for me in the meanwhile, though it would be neater to have a specific configuration value for this so we can use the `header` value solely for documenting purposes.

I will see if I have time later to come up with a suggestion.

Thanks!

**Comment by RReverser** [comment]
Can't you generate bindings to a string? Then you can add any lines you want before writing to an actual file.
