### ISSUE TITLE
Swift bindgen 

### ISSUE THREAD

**Issue by adamnemecek** [eqrion/cbindgen#420]
I'm considering adding a language option to cbindgen for Swift. 

The Swift compiler lets you include a C header which, when annotated with the CF_SWIFT_NAME macro exposes the C code to Swift code as Swift (so that one doesn't need to for example explicitly pass `self`/`this` to functions, similarly as with C++ cbindgen). 

Here's more info
https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/customizing_your_c_code_for_swift

Is there any interest in this feature?

**Comment by emilio** [comment]
If you have a use case for this and it is not very invasive, I'd say go for it :)

This needs to have tests, which may be the trickiest part... Would this be testable in non-apple platforms?
