### ISSUE TITLE
Cbindgen output is sometimes empty

### ISSUE THREAD

**Issue by Luni-4** [eqrion/cbindgen#427]
I tried to run `cbindgen` on this [project](https://github.com/rust-av/av-metrics). I tend to precise that I'm the creator of the `cbindgen.toml` file of the project, so if there is any error in it, I can change its content.

Practically, if I choose to run `cbindgen` on the `capi.rs` file, as shown by the following code, it works.

```
use std::path::Path;

fn main() {
    let include_path = Path::new("av_metrics.h");
    let src_path = Path::new("/your/path/to/av-metrics/av_metrics/src/capi.rs");

    let mut config = cbindgen::Config::from_root_or_default(src_path);
    cbindgen::Builder::new()
        .with_src(src_path)
        .with_config(config)
        .generate()
        .unwrap()
        .write_to_file(include_path);
}
```
On the other hand, if I use the entire crate, it doesn't always work. You can see the problem running the following code many times. 

```
use std::path::Path;

fn main() {
    let include_path = Path::new("av_metrics.h");
    let crate_path = Path::new("/your/path/to/av-metrics/av_metrics/");

    let mut config = cbindgen::Config::from_root_or_default(crate_path);
    cbindgen::Builder::new()
        .with_crate(crate_path)
        .with_config(config)
        .generate()
        .unwrap()
        .write_to_file(include_path);
}
```

I also tried to run the two approaches above using the CLI, and I got the same results.

Thanks in advance for your help!

**Comment by emilio** [comment]
Hi, can you give concrete STR with the CLI? This should probably be looked at.

Is it just `cbindgen /path/to/av-metrics`?

**Comment by Luni-4** [comment]
> Hi, can you give concrete STR with the CLI? This should probably be looked at.
>
> Is it just `cbindgen /path/to/av-metrics`?

Hi, @emilio!

I've tried different options inside the `av-metrics/av_metrics/ ` directory:
- `cbindgen --config cbindgen.toml --output av_metrics.h --clean .`
-  `cbindgen --config cbindgen.toml --output av_metrics.h --clean /my/absolute/path/to/av-metrics/av_metrics`
-  `cbindgen --config cbindgen.toml --output av_metrics.h .`
-  `cbindgen --config cbindgen.toml --output av_metrics.h /my/absolute/path/to/av-metrics/av_metrics`

None of them worked.

This one always worked instead:
-   `cbindgen --config cbindgen.toml --output av_metrics.h src/capi.rs` 

I've used the `master` branch to run these tests.

**Comment by Luni-4** [comment]
After having installed `Rust 1.40`, the problem was gone. Probably a `cargo` issue? I don't know. I will reopen if it appears again.

Thanks again for your help, @emilio! :)

**Comment by TomzBench** [comment]
Just leaving this here for myself later.

I noticed that if I have 2 crates that are the same name, and rely on proc macro expansion, it seems that intermittently, probably depending on which is compiled first, causes empty output because the wrong crate gets expanded.

For example, if I have `.with_parse_expand(&[foo])`  ...and there are 2 foo crates.  And you rely on proc macros from `foo` to generate your ffi functions, you will sometimes generate empty header file. Likely, because the "other" foo crate is expanded.  

Perhaps it is a good idea that `.with_parse_expand` should except regex, or multiple instances with the crate name.

**Comment by tgross35** [comment]
Another thing that I always forget is that functions that aren't `#[no_mangle]` don't show up. Maybe there should be a "FAQ: my bindings are empty"
