### ISSUE TITLE
forward declare types that couldn't be found

### ISSUE THREAD

**Issue by NickeZ** [eqrion/cbindgen#428]
I have a struct in a dependency which cbindgen emits "WARN: can't find XY" for. I only use pointers to it in the interface. Would it be possible to forward declare such structs?

**Comment by emilio** [comment]
I think it should already work if you set `parse_deps = True`?

**Comment by NickeZ** [comment]
Aha didnt know about that. Ill try as soon as il back at work

**Comment by NickeZ** [comment]
Kind of worked. Got another error and opened another issue.
