### ISSUE TITLE
Issue parsing protobuf crate

### ISSUE THREAD

**Issue by NickeZ** [eqrion/cbindgen#429]
Hi there!

I got an error compiling protobuf, and no error running the compiler.

```
ERROR: Parsing crate `protobuf`:`/home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.8.1/src/reflect/accessor.rs`:
Error("expected one of: identifier, `::`, `<`, `_`, literal, `ref`, `mut`, `&`, parentheses, square brackets, `..`")
Try running `rustc -Z parse-only /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.8.1/src/reflect/accessor.rs` to see a nicer error message
ERROR: Couldn't generate bindings for ../../.
```

```
$ rustc -Z parse-only /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.8.1/src/reflect/accessor.rs
error: the option `Z` is only accepted on the nightly compiler
```

```
$ rustc +nightly -Z parse-only /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.8.1/src/reflect/accessor.rs
```

**Comment by emilio** [comment]
Hmm, it sounds like syn is failing to parse something that the compiler accepts... I'd file an issue in `syn` with the contents of that file.

if you don't need types from that crate you can probably explicitly specify the dependencies you need the type for (via `[export.include]`).

**Comment by NickeZ** [comment]
Is there any configuration for specifying which dependency to traverse into? Because it would be enough if cbindgen looks at one of the dependencies and in my case it doesn't need to recurse either.

**Comment by emilio** [comment]
I meant, `export.include` is what specifies which dependencies you parse. If the problematic dependency is not there I expect cbindgen not to panic.

**Comment by NickeZ** [comment]
Are we talking about the same thing:

```
[export]
# A list of additional items to always include in the generated bindings if they're
# found but otherwise don't appear to be used by the public API.
#
# default: []
include = ["MyOrphanStruct", "MyGreatTypeRename"]
```

How would this help me? I'm using the types. They are simply defined in a sub-crate.

**Comment by emilio** [comment]
Err, sorry, I meant `parse.include`, I can't type today apparently.

```
# A white list of crate names that are allowed to be parsed. If this is defined,
# only crates found in this list will ever be parsed.
#
# default: there is no whitelist (NOTE: this is the opposite of [])
include = ["webrender", "webrender_traits"]
```

**Comment by NickeZ** [comment]
Cool, yeah that makes more sense and that worked great! I have however one more question. One of the types is an `std` type. Again I only need an opaque pointer to it. What do I need to do?

**Comment by emilio** [comment]
Hmm... Which type is this? I think right now you can fool cbindgen by defining a type with the same name in a submodule, but that is not awesome for various reasons.

**Comment by NickeZ** [comment]
It is `Waker`
