### ISSUE TITLE
Fails with new `Cargo.lock` format

### ISSUE THREAD

**Issue by otavio** [eqrion/cbindgen#436]
`cargo` has enabled the new format by default[1] and this causes the `cbindgen` to fail to parse the dependencies.

1. https://github.com/rust-lang/cargo/pull/7579

It fails at https://github.com/eqrion/cbindgen/blob/master/src/bindgen/cargo/cargo.rs#L125 as the new format does not has the version annotated on the same line.

**Comment by emilio** [comment]
Thanks for filing, will take a look.

**Comment by est31** [comment]
One could switch to the cargo crate to parse the Cargo.lock format, but this would hopelessly inflate the number of dependencies as it would include everything cargo is depending on. Ideally, one could ask the cargo maintainers to extract the Cargo.lock parsing code into a separate crate and to then use that.

**Comment by emilio** [comment]
I had to catch up with the lockfile changes, but I think https://github.com/eqrion/cbindgen/pull/438 should be enough.

**Comment by otavio** [comment]
> I had to catch up with the lockfile changes, but I think #438 should be enough.

I tested the PR and it worked just fine. Thanks for looking at it.
