### ISSUE TITLE
Possible to remove the `_` in mangle_path for C?

### ISSUE THREAD

**Issue by adamski** [eqrion/cbindgen#437]
We have a generic type being exposed to C. Mangle path adds an underscore between the types. Is it possible to configure this, as it messes with the project's code style :)

**Comment by emilio** [comment]
Well, I guess we could add options to configure it, but off-hand you need _some_ sort of mangling scheme.

**Comment by emilio** [comment]
I guess a minimal approach to do this would be to add a new configuration option like `mangling_separator` or something, which is a string. That'd allow you to use the empty string to remove them all.

If that seems reasonable it shouldn't be hard to implement...

**Comment by adamski** [comment]
That sounds good to me! I'm up for having a go at a PR for that.

**Comment by emilio** [comment]
Sure, please go for it :)

**Comment by emilio** [comment]
This was fixed in #502.
