### ISSUE TITLE
`doc` attribute doesn't behave like rustc does

### ISSUE THREAD

**Issue by TheKK** [eqrion/cbindgen#442]
Inputs
---

```rust
#[no_mangle]
#[doc = "a \n b"]
pub extern "C" fn example_a() {}
```

and

```rust
#[no_mangle]
#[doc = "a \n\n b"]
pub extern "C" fn example_b() {}
```

Rendered rustdoc
---
[rustdoc/the doc attribute](https://doc.rust-lang.org/rustdoc/the-doc-attribute.html)

![圖片](https://user-images.githubusercontent.com/5238484/71337544-22a0d600-2587-11ea-9905-b7483eb65788.png)

![圖片](https://user-images.githubusercontent.com/5238484/71337575-3f3d0e00-2587-11ea-9504-f38aad154490.png)

Actual generated header
---

```cpp
///a
 b
void example_a();
```

```cpp
///a

 b
void example_b();
```

Expected generated header
---

```cpp
///a b
void example_a();
```

```cpp
///a
///
///b
void example_b();
```

This happens when I'm trying to generate multi-line comments with macro. Looks like ([code](https://github.com/eqrion/cbindgen/blob/16fe3ec142653277d5405d9a6d25914d925c9c3c/src/bindgen/utilities.rs#L252)) we simply use value in single `doc` attribute directly without any modification (like rustdoc does).

BTW, I'm happy to help this out :)

**Comment by emilio** [comment]
Yeah, it'd be great to get this fixed :)

**Comment by TheKK** [comment]
After some researching I got some questions. Should I implement this translation by myself or using other crate?

One thing that bother me is that the spec of markdown line break is a bit vague. The algorithm isn't obvious to me. It might works for most cases but I'm afraid there would be missing one :(

Using crate might be overkill, on the other hand.

Any suggestions?

**Comment by emilio** [comment]
Can you clarify? I (maybe naively) was thinking that just unescaping `\n` would do.

Why isn't this just a matter of splitting/un-escaping `\n` characters in the `#[doc]` attribute? I don't think we need to generate perfect markdown, just not generate broken code.

**Comment by TheKK** [comment]
> Can you clarify? I (maybe naively) was thinking that just unescaping \n would do.

I found that line end with **two space** is the other case markdown would cause line break. 

Maybe my concern here is that should we expect the Rust source file used for generating **good** C/C++ header, also generating **good** Rust document using `rustdoc`?  I think this might depends on use case.

(good means correct line break)
