### ISSUE TITLE
Macro expansion breaks w/rental crate

### ISSUE THREAD

**Issue by mattfs** [eqrion/cbindgen#444]
When using `[parse.expand]` and the `rental` crate, the bindings fail to generate. It looks like there is a strange artifact in macro expansion output: there's some trait bounds that are empty?

Attached is a minimal repro for this bug. It _might_ be an upstream Rust issue where Rust is allowing `rental` to generate invalid type bounds.

Playground link containing the expanded macro output. Notice this oddly generated code which seems to come from `rental` here: https://github.com/jpernst/rental/blob/master/rental-impl/src/lib.rs#L423

```        #[doc =
          r" The closure may return any value not bounded by one of the special rental lifetimes of the struct."]
        pub fn rent<__F, __R>(&self, f: __F) -> __R where
         __F: for<'t, 'm> __rental_prelude::FnOnce(&'t (Foo<'m, i32>)) -> __R,
         __R {
            f(&self.t)
        }
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ac7e0dde8adb6601a553502c6d6caf6f

[repro.zip](https://github.com/eqrion/cbindgen/files/4013627/repro.zip)

**Comment by emilio** [comment]
Haven't looked deeply, but this is probably a bug in `cargo expand` rather than `cbindgen`.

**Comment by emilio** [comment]
Err, sorry, on `rustc` with `--pretty=expanded`

**Comment by mattfs** [comment]
@emilio I think you are correct on this one. I will file a core bug.

**Comment by emilio** [comment]
Ok, let me know if that doesn't progress or there's something to fix in cbindgen, thanks!
