### ISSUE TITLE
Can cbindgen extract pub constants from a dependency?

### ISSUE THREAD

**Issue by jadamcrain** [eqrion/cbindgen#445]
I have a workspace where I have one crate with my pure rust API, and another that is the C FFI interface:

https://github.com/automatak/rodbus

I'd like to be able to get [these constants](
https://github.com/automatak/rodbus/blob/master/rodbus/src/constants.rs) from the main crate into the C headers. Is this possible? I tried setting `include =["rodbus"]` put it didn't seem to pick up the constants. If I redefine them in the FFI lib.rs from the constants in the other library, it doesn't like the format.

What's the best course of action here to avoid duplication?

Another issue:

Can I force cbindgen to define forward declarations to structs that I want to use as opaque pointer types? ATM, I've created a prelude.h that defines them, and then I have cbindgen add the include for that file, but I'd prefer if I could get cbindgen to do it, or have it include arbitrary lines to avoid having multiple header files.

Thanks so much for this awesome tool!

**Comment by emilio** [comment]
I think you need `parse_deps = true`, then it should work... Does it?

**Comment by jadamcrain** [comment]
Not on it's own. The trick was the 'extra_bindings` field as well:

```
[parse]
parse_deps = true
include = ["rodbus", "tokio"]
extra_bindings = ["rodbus"]
```

It take it there's no way to whitelist modules to process?

**Comment by emilio** [comment]
Ah, true, I added `extra_bindings` to deal with this exactly, as for some reason we never exported constants from other crates.

cbindgen generally isn't very module-aware... I'd be happy to take a patch to make it a bit more module-aware, but otherwise no, not atm.

**Comment by jadamcrain** [comment]
Ok, cool. We'll keep it in mind. ATM we're happy with duplicated a handful of constants. The tool is serving our needs nicely.
