### ISSUE TITLE
Keep order of exported functions

### ISSUE THREAD

**Issue by systec-ad** [eqrion/cbindgen#461]
Hi,

In my project all `extern "C" pub fn`'s are declared in a single file / module.
Is it possible to ensure that the order of the generated exported functions in the header keeps same as in the module?

To me it seems that the functions are ordered by the functions name. Am I correct about this? Is there a way of changing / workaround this?

**Comment by emilio** [comment]
That is:

https://github.com/eqrion/cbindgen/blob/eb9cce693438d2cc6fe3d74eb5a56aa50094f68f/src/bindgen/library.rs#L58

So there's no way to workaround it at the moment. But it would be reasonable to add a config switch to avoid this. If you want to send a PR for that I'd be happy to review it :)
