### ISSUE TITLE
Don't warn if both #[no_mangle] and extern "C" are missing

### ISSUE THREAD

**Issue by Barugon** [eqrion/cbindgen#467]
I have a number of functions that I don't want exported through a C ABI but I'm getting warnings. This clutters the output and makes it more difficult to see real issues. I suggest that if a function is missing both #[no_mangle] and export "C" then the code author intends that the function should not be exported and there should be no warning. If just one or the other is missing then that is an actual issue.

**Comment by emilio** [comment]
that's fair, should be pretty easy to fix.

**Comment by Barugon** [comment]
I'm actually getting more warnings in 0.13.0. Also, this line is missing a closing parenthesis in the text:
https://github.com/eqrion/cbindgen/blob/4d2b2026b6b6f03f709305243e041be9a6a7a580/src/bindgen/parser.rs#L659

**Comment by Barugon** [comment]
Just to be clear, this is correct, generates header file output and does not print any warnings:

```Rust
#[no_mangle]
pub extern "C" fn foo() {
}
```

This does not generate header file output and should print a `#[no_mangle]` warning:

```Rust
pub extern "C" fn foo() {
}
```

This does not generate header file output and should print a `extern "C"` warning:

```Rust
#[no_mangle]
pub fn foo() {
}
```

This does not generate header file output and should not print any warning:

```Rust
pub fn foo() {
}
```

**Comment by emilio** [comment]
Sure, I totally agree with that. I don't plan to work on this short term, should be a pretty easy bug for somebody to get involved with the codebase :)

**Comment by Barugon** [comment]
No worries. I'll look at coming up with a fix for this.

**Comment by TheKK** [comment]
I'd like to help this issue, can I :)

**Comment by TheKK** [comment]
Should we discard warning when function is not marked as `public`?

**Comment by Barugon** [comment]
@TheKK 
I haven't had time to look at this but I would think that warnings would be generated for these conditions:

- `extern "C"` and `#[no_mangle]` but not `pub`
- `pub extern "C"` but not `#[no_mangle]`
- `#[no_mangle]` but not `extern "C"`

If the function is `pub` without `extern "C"` and `#[no_mangle]` then no warning should be generated.

**Comment by emilio** [comment]
> I'd like to help this issue, can I :)

Please do! No need to ask :)
