### ISSUE TITLE
Ability to define a struct as void

### ISSUE THREAD

**Issue by wagenet** [eqrion/cbindgen#468]
I'd like to expose an internal Rust struct but keep its contents hidden from C. The C code passes around a pointer to the struct but never has to actually look at it. I'd like to be able to do something like the following:

```rust
struct Foo {
   // ...
}
```

```h
typedef void Foo;
```

**Comment by emilio** [comment]
This should work shouldn't it? It wouldn't be void, but just a forward declaration in C, so like `struct Foo;`. Why is `void` desirable?

**Comment by wagenet** [comment]
@Emilio my case is probably unusual, but I don't want any of the internals exposed. The C code that calls it doesn't need to know anything about the contents of the struct, just that it exists.

**Comment by emilio** [comment]
Right, but that's exactly what that does, isn't it? For a concrete example, the following rust code:

```rust
pub struct MyRustStruct {
    something_very_secret: u64,
}

#[no_mangle]
pub extern "C" fn do_x(something: &MyRustStruct) {
}
```

Generates the following C++ code:

```cpp
#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>

struct MyRustStruct;

extern "C" {

void do_x(const MyRustStruct *something);

} // extern "C"
```

There's no way for the C++ code to know about `something_very_secret`, or am I missing something?

**Comment by wagenet** [comment]
@emilio it's entirely possible I'm thinking about this the wrong way. C isn't my strong suit. Let's assume this is a non-issue for now. I find something that makes me think it's still a problem I'll re-file. Thanks for your time.
