### ISSUE TITLE
Fix generated typedefs for function types without arguments

### ISSUE THREAD

**Issue by Foxhound31** [eqrion/cbindgen#470]
For type 
`pub type Function = fn() -> usize;`
generated C typedef is
`typedef uintptr_t (*Function)();`
but expected according to C standard is
`typedef uintptr_t (*Function)(void);`
It implies warning when compiling C code:
`warning: function declaration isn't a prototype`

**Comment by emilio** [comment]
Should be an easy one to fix.

**Comment by TheKK** [comment]
Can I have this one :)

**Comment by emilio** [comment]
Sure! Please go ahead. Thanks!
