### ISSUE TITLE
Add `Box<T>` to the supported types, where `T: Sized`

### ISSUE THREAD

**Issue by eliaslevy** [eqrion/cbindgen#474]
As of Rust 1.41.0:

>  `Box<T>`, where `T: Sized` is now ABI compatible with the C language's pointer (`T*`)
> types. So if you have an `extern "C"` Rust function, called from C, your Rust function can
> now use `Box<T>`, for some specific `T`, while using `T*` in C for the corresponding function.

(from [Announcing Rust 1.41.0](https://blog.rust-lang.org/2020/01/30/Rust-1.41.0.html#more-guarantees-when-using-boxt>-in-ffi))

So that
```
#[no_mangle]
pub extern fn test() -> Box<i32> { Box::new(1i32) }
```
should generate
```
int32_t * test();
```

**Comment by emilio** [comment]
This makes sense. To be clear, you can already do this in C++ if you do:

```
template <typename T> using Box = T*;
```

For C, and maybe for function arguments, we probably want to do this automagically.

The reason why I think we shouldn't do it automatically for C++ members and such is that in C++ having `Box<T>` is actually useful (if you don't care about `Box` parameter-passing).

See also the discussion in #451

**Comment by mgeier** [comment]
> For C, and maybe for function arguments, we probably want to do this automagically.

Are there any news on this?

It would be great to have this!

**Comment by emilio** [comment]
https://github.com/eqrion/cbindgen/commit/4ce324c fixed this.

**Comment by mgeier** [comment]
Thanks @emilio, this works great!
