### ISSUE TITLE
Skipped functions: not both `no_mangle` and `extern "C"`

### ISSUE THREAD

**Issue by dbrgn** [eqrion/cbindgen#49]
When trying to generate header files for an FFI crate I get these warnings:

> WARN: skip ::svg_str_to_polylines - (not both `no_mangle` and `extern "C"`)
> WARN: skip ::free_polylines - (not both `no_mangle` and `extern "C"`)

The warnings are correct, I use `#[no_mangle]` for the functions but not `"C"`:

```rust
#[no_mangle]
pub extern fn svg_str_to_polylines(...
```

According to https://stackoverflow.com/a/44664851/284318 there is not a real need for the `"C"` part, and the version without seems preferred: https://github.com/rust-lang-nursery/fmt-rfcs/issues/52

Is there a reason why cbindgen requires that part of the declaration?

**Comment by eqrion** [comment]
Ah, I wasn't aware that the C ABI is the default with `extern`. cbindgen should accept it without "C" then.

**Comment by eqrion** [comment]
This should be fixed in e0ec983930a318ef1a4016164799e24a248ef93b.
