### ISSUE TITLE
Struct is emitted as opaque type if its fields are declared using macro

### ISSUE THREAD

**Issue by broadwaylamb** [eqrion/cbindgen#517]
I have the following code, where I use a macro to declare struct fields for convenience:

```rust
macro_rules! declare_renderer_routine {
    (($($args:ty),*) -> $ret_ty:ty) => {
        Option<fn(Option<*mut c_void>, $($args,)* *const c_void, fn(*const c_void) -> ()) -> ()>
    }
}

#[repr(C)]
pub struct PolymorphicRenderer {
    pub renderer_ctx: Option<*mut c_void>,
    pub clear_screen: declare_renderer_routine!(() -> ()),
    pub flush: declare_renderer_routine!(() -> ()),
    pub move_cursor_to: declare_renderer_routine!((i32, i32) -> ()),
    pub set_color: declare_renderer_routine!((Color) -> ()),
}
```

This struct is emitted as:

```C
typedef struct PolymorphicRenderer PolymorphicRenderer;
```

cbindgen doesn't expand the macros?

**Comment by emilio** [comment]
no, it does not unless you tell it to, see `[parse.expand]` in the docs. It should work with that but let me know otherwise.

`Option<*mut c_void>` is also not FFI-safe, you need to use `Option<NotNull<c_void>>`, or just `*mut c_void`.

Let me know if `[parse.expand]` doesn't work though.

**Comment by broadwaylamb** [comment]
Oh, I didn't read the docs carefully enough.

Anyway, I've already rewritten my code so I don't need it.

And thanks for mentioning about `Option<*mut c_void>`! I din't know that.

**Comment by broadwaylamb** [comment]
@emilio unfortunately, it doesn't work.

**Comment by emilio** [comment]
What doesn't work?

**Comment by broadwaylamb** [comment]
You need Cargo to be from a nightly toolchain, otherwise macro expansion command fails with:

```
error: the option `Z` is only accepted on the nightly compiler
```

So I need to run set the `RUSTC` environment variable to a `rustc` binary from a nightly toolchain, like so:

```
export RUSTC=~/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/rustc
cbindgen -o "myheader.h"
```

It would be great if this was mentioned in the documentation.
