### ISSUE TITLE
Exclude parsing of module paths in crate

### ISSUE THREAD

**Issue by MarkMcCaskey** [eqrion/cbindgen#518]
Hello!  I ran into an issue with cbindgen where I want to expose multiple C interfaces in a single static/dynamic library but want to avoid including one of these interfaces in the generated header file.

The reason for this is that our Wasm runtime has a C API but we also want to support the standard Wasm C API which has its own header files with extra information in them.  It'd be somewhat confusing if the generated header file duplicated these definitions as it's missing important logic that's implemented in the standard header file.

I tried conditionally including the module with the standard definitions with a cargo feature and using the `parse.expand` options but ran into issues, one of which was that it required nightly Rust.  So I tried splitting out the standard definitions into another crate and reexporting them but due to https://github.com/rust-lang/rfcs/issues/2771 this didn't actually work out (I got the linking to work correctly on OSX and Windows but not on Linux).

Due to the size of this API and the fact that we're using macros to generate many functions, it'd be really nice to not have to manually blacklist each definition.  Ideally there would be a way to tag a module path as excluded from parsing by cbindgen.  Alternatively, a way to pass features for parsing without needing to `cargo expand` it might solve this problem too. 

I'm open to alternatives and at some indeterminate point in the future some of my previous attempts may work, but it seems that this capability could still be useful.

Please let me know if this is a feature that you're interested in!

**Comment by emilio** [comment]
Can you post a concrete example so that I can wrap my head around it please?

You can conditionally import / define stuff using `#[cfg]`, but I understand that what you want is to completely ignore a module, right?

I wonder if something like:

```rust
#[cbindgen::ignore]
mod foo;
```

or such?

**Comment by MarkMcCaskey** [comment]
Sure, but the example you gave is pretty much exactly it! In `lib.rs` I have a module and I'd like it to be compiled into the library but not parsed by cbindgen and used in the header file generation.

So we have:

foo.rs:
```rust
pub struct baz;

#[no_mangle]
pub extern bar(arg: baz) {}
```

lib.rs:
```rust
mod other_module;
// I'd like to not include foo in cbindgen's parsing
mod foo;
```

`bar` and `baz` should ideally not be in the generated header file but everything else should be.

We're running cbindgen from `build.rs` -- I forgot to mention that!

A custom attribute seems like it would work!

I wasn't able to find a way to use cargo features to allow the module to be included in the library but not seen by cbindgen without nightly cargo/rust when using cbindgen from a build.rs.

**Comment by emilio** [comment]
So what about https://github.com/eqrion/cbindgen/pull/519? Could you give that a spin and tell me if that works for you? I added some docs to the documentation in the last commit.

**Comment by MarkMcCaskey** [comment]
It seems to work perfectly!!  Thank you so much!  And thanks for doing it so quickly -- sorry about my delay in verifying it for you

**Comment by MarkMcCaskey** [comment]
Following up on this: I just realized I made a mistake when testing!  I was working with 2 source trees in different directories and I had confused them in a way where I applied half the edits to one and half the edits to the other in a way that I thought it worked but I wasn't actually testing.

I just fixed it and investigated it and it didn't appear to work at all: on mod statements in lib.rs or individual items, so I skimmed through the PR diff and found https://github.com/eqrion/cbindgen/pull/519/files#diff-78f4a086c443ce2cfc7108d107ae2c50R100 which has `cbindgen:ignore` (note the single `:`) which looked like a typo, so I tried it with a single `:` and it works perfectly, both on items and on mod statements in lib.rs!  Thanks!!

**Comment by emilio** [comment]
Oh, ineed, the docs have a typo.

I initially implemented it using custom attributes like `#[cbindgen::ignore]`, but turns out that we can't really do that nicely, as those need to be whitelisted by rustc apparently. So the rust code would error out.

So I used the regular annotation system that we have, which uses `cbindgen:` with a single colon. But apparently goofed updating the docs, lol.
