### ISSUE TITLE
How to reexport external type?

### ISSUE THREAD

**Issue by saschanaz** [eqrion/cbindgen#523]
I'm trying to generate bindings for functions returning [external struct](https://docs.rs/winapi/0.3.8/winapi/shared/guiddef/struct.GUID.html):

```rs
use winapi::shared::guiddef::GUID;

const SAMPLEIME_CLSID: GUID = get_guid_from_i128(0x89adf27c_0863_4ad3_a463_f7ecfc75d01d);

#[no_mangle]
pub extern fn get_clsid() -> *const GUID {
  return &SAMPLEIME_CLSID;
}
```

Here, I intend to map `GUID` to [its original C definition](https://docs.microsoft.com/en-us/windows/win32/api/guiddef/ns-guiddef-guid).

Currently cbindgen generates the following with two warnings:

```
WARN: Skip globals::SAMPLEIME_CLSID - (not `pub`).
WARN: Can't find GUID. This usually means that this type was incompatible or not found.
``` 

```
#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>

extern "C" {

const GUID *get_clsid();
```

Is there a way to tell cbindgen that `GUID` is from external C definition and insert a proper header?

**Comment by emilio** [comment]
We just use a special [header](https://searchfox.org/mozilla-central/rev/8bc4e35c9bb47c1fe3131e6155d9f482e1efef9a/servo/ports/geckolib/cbindgen.toml#33) that pulls in all the types that cbindgen doesn't understand.

So you could just add `sys_includes = ["guiddef.h"]` in this case, unless I'm missing something.

Or do you want to also generate `SAMPLEIME_CLSID`?

**Comment by saschanaz** [comment]
> So you could just add `sys_includes = ["guiddef.h"]` in this case, unless I'm missing something.

Thanks, this works! But it doesn't suppress warnings, is there a way to suppress them?

> Or do you want to also generate `SAMPLEIME_CLSID`?

If possible. Doing `pub const SAMPLEIME_CLSID` shows a different message: `WARN: Skip globals::SAMPLEIME_CLSID - (Unhandled const definition)`, not sure why.

**Comment by emilio** [comment]
> > So you could just add `sys_includes = ["guiddef.h"]` in this case, unless I'm missing something.
> 
> Thanks, this works! But it doesn't suppress warnings, is there a way to suppress them?

Hmm, not really, afaict. It's unclear when it'd be safe to suppress them without parsing all the C code, including includes...

> > Or do you want to also generate `SAMPLEIME_CLSID`?
> 
> If possible. Doing `pub const SAMPLEIME_CLSID` shows a different message: `WARN: Skip globals::SAMPLEIME_CLSID - (Unhandled const definition)`, not sure why.

That is just because cbindgen is not magic, it's just a kinda dumb parser. So it can't execute `get_guid_from_i128` and just bails instead...

In order to be able to generate that constant, it would need to know about `GUID`, and it'd need to execute that function and somehow represent the result in C++ code. Better integration between rustc and cbindgen would be great, but it's tricky.

**Comment by saschanaz** [comment]
>It's unclear when it'd be safe to suppress them without parsing all the C code, including includes...

I think it can get a manual configuration, something like `external_c_type = ["GUID"]`.

**Comment by saschanaz** [comment]
> That is just because cbindgen is not magic, it's just a kinda dumb parser. So it can't execute `get_guid_from_i128` and just bails instead...

Oh wait, why does it need to run the function when the declaration itself already has its type?

**Comment by emilio** [comment]
Because `const FOO` in rust is not the same as `#[no_mangle] static FOO`.

**Comment by saschanaz** [comment]
Oh got it. Thank you very much for details 👍

Now the only issue is the warnings that can't be suppressed, should I file a new issue about it and close this?

**Comment by emilio** [comment]
Yes, let's do that. Thanks!
