### ISSUE TITLE
How to handle export prefix and incomptaible/not found types

### ISSUE THREAD

**Issue by wasaylor** [eqrion/cbindgen#530]
cbindgen 0.14.2
rustc 1.43.0

I have a fn that returns a `libc::timespec`, and my cbindgen.toml adds an include for time.h, however cbindgen is producing this warning:

```
WARN: Can't find timespec. This usually means that this type was incompatible or not found.
```

Because my cbindgen.toml _also_ is using export prefix, I'm getting something like `prefix_timespec` in the header file.

 Is there a way to handle this so that it just exports `timespec` without modifying the header file post-cbindgen ?

Thank you

**Comment by emilio** [comment]
yes. A bit hacky, but there's `renaming_overrides_prefixing`, and then you could "rename" `timespec` to itself.

**Comment by wasaylor** [comment]
Thank you!  This will work for now.

 Does the project expect to eventually support all of libc's types?

**Comment by emilio** [comment]
I don't think that's in scope, where to stop otherwise? :)
