### ISSUE TITLE
Invoke cbindgen in command line from other directory.

### ISSUE THREAD

**Issue by amCap1712** [eqrion/cbindgen#537]
Is it possible to invoke cbindgen from another directory that is different from where my Cargo.toml file is present ? If not, it would be desirable to add a flag to pass the path to the Cargo.toml . Is this feasible ? Are there some intrinsic issues which prohibit having this feature ? If not, I'd be happy to try and add this.

**Comment by emilio** [comment]
Yes, cbindgen takes the crate directory as an argument. What am I missing?

**Comment by emilio** [comment]
From `cbindgen --help`:

```
ARGS:
    <INPUT>    A crate directory or source file to generate bindings for. In general this is the folder where the
               Cargo.toml file of source Rust library resides.
```

But let me know if that's not what you want.
