### ISSUE TITLE
Generation requires strings instead of AsRef<Path>

### ISSUE THREAD

**Issue by Michael-F-Bryan** [eqrion/cbindgen#54]
Most Rust APIs which work on the file system can accept anything which is `AsRef<Path>`, however `cbindgen::generate()` and `write_to_file()` only accept `&str`. Is there any chance you could make these user-facing functions more generic/lenient in what they accept?

**Comment by eqrion** [comment]
I updated the API in 6551eea08d270e4ef8e689fa56d41378d0a1271b. Thanks!
