### ISSUE TITLE
A better error message for unsupported unnamed parameters

### ISSUE THREAD

**Issue by DarkEld3r** [eqrion/cbindgen#543]
`cbindgen` gives the "Parameter has an unsupported type" error for the following code:
```rust
use std::os::raw::c_char;

#[no_mangle]
pub extern "C" fn foo(_: c_char) {
    todo!()
}
```
The command that I used to generate the header:
```shell
cbindgen --config cbindgen.toml --crate bt --output my_header.h --lang c
```

I have spent some time trying to understand what was wrong with `c_char` (`libc::c_char`), till I figured that I should give a name to this parameter.

**Comment by emilio** [comment]
Ah, that seems like a bug. I don't see why you wouldn't be able to generate that function. We could just generate nameless arguments, which are legal in C (so that would generate `void foo(const char*);` or such).

**Comment by DarkEld3r** [comment]
I have updated the description with a little bit more details on how to reproduce this issue.

**Comment by emilio** [comment]
Huh, I somehow re-discovered this bug while doing some refactoring, it's fixed in master via https://github.com/eqrion/cbindgen/pull/550.
