### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by liuqi-sun** [eqrion/cbindgen#547]
There was an error When execute cargo install --force cbindgen 。

Updating crates.io index
error: failed to download `cbindgen v0.14.3`

Caused by:
  failed to enable HTTP2, is curl not built right?

Caused by:
  [1] Unsupported protocol

**Comment by emilio** [comment]
That seems like a cargo issue doesn't it? Can you install other crates?

**Comment by emilio** [comment]
Closing for now because this doesn't look like a cbindgen issue and I got no reply, but please reopen if it turns out to be.
