### ISSUE TITLE
Option of function pointer type is not simplified to function pointer type.

### ISSUE THREAD

**Issue by jrmuizel** [eqrion/cbindgen#552]
```rust
pub type VoidPtrToSizeFn = fn () -> ();

#[no_mangle]
pub extern "C" fn root(
    c: Option<VoidPtrToSizeFn>,
) { }
```

translates to:
```c
template<typename T>
struct Option;

using VoidPtrToSizeFn = void(*)();

extern "C" {

void root(Option<VoidPtrToSizeFn> c);

} // extern "C"
```

when it should translate to:
```c
using VoidPtrToSizeFn = void(*)();

extern "C" {

void root(VoidPtrToSizeFn c);
```

The simplification happens properly if there's no type definition. Do we have a mechanism for seeing through type definitions?

**Comment by emilio** [comment]
This is a dupe of https://github.com/eqrion/cbindgen/issues/326. I think this should be fixable, just a bit annoying maybe in presence of `#[cfg]`'d stuff...
