### ISSUE TITLE
New patch version breaks all new builds of our project

### ISSUE THREAD

**Issue by rzumer** [eqrion/cbindgen#567]
Hello,
The commit https://github.com/eqrion/cbindgen/commit/bf78df1996396d32e4d004da04c3149f5ae4c219 causes the [rav1e](https://github.com/xiph/rav1e/) C API to fail to build, retroactively for all versions using cbindgen 0.14.
Even if this is due to an incorrect/unsupported use of `cbindgen` (I think it's related to #528), I'd appreciate if this breaking change could be released as a minor version rather than a patch version.
Thanks.

**Comment by emilio** [comment]
Ah, sorry, I missed this one. Thank you for the ping, we should probably yank that version. Though as you noted the functions were incorrect before / would generate wrong code when called.

Do you have an example of the brokenness? Did it fail to build just by exposing less functions?

**Comment by rzumer** [comment]
Yes, it's a build break.

It should be reproducible on [this](https://github.com/xiph/rav1e/commit/a9de35d012c9b03cddab6ce889d720d47a36b967) commit, when building the C library via `cargo install cargo-c && cargo cinstall --release`. Without a `Cargo.lock` file `cargo-c` will pull the breaking patch version and the build will fail.

**Comment by emilio** [comment]
I think realistically that patch was a bugfix. I'll jank the version anyways, see #594. But let's close this. Will try to do better in the future, though this particular incident still seems there's not much to blame on cbindgen's side, it was generating invalid code before.
