### ISSUE TITLE
Ignore annotation not work

### ISSUE THREAD

**Issue by FourLeafTec** [eqrion/cbindgen#572]
I have a project like following:

```
-src
  |-server
      |-mod.rs
      |-server.rs
      |-defines.rs
  |-lib.rs
```

defines.rs
```
use websocket::OwnedMessage;

pub type SinkContent = websocket::client::r#async::Framed<
    tokio::net::TcpStream,
    websocket::r#async::MessageCodec<OwnedMessage>,
>;
pub type SplitSink = futures::stream::SplitSink<SinkContent>;
```
when scan defines.rs will error:
```
thread 'main' panicked at 'SplitSink is not generic', /Users/flt/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/cbindgen-0.9.1/src/bindgen/ir/typedef.rs:158:9
```

So, i try to ignore this mod
then i add ignore annotation to mod.rs:
```
pub mod server;

/// cbindgen:ignore
pub mod defines;
```

but the ignore not work, cbindgen also error:
```
thread 'main' panicked at 'SplitSink is not generic', /Users/flt/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/cbindgen-0.9.1/src/bindgen/ir/typedef.rs:158:9
```

**Comment by emilio** [comment]
Can you attach a more reduced test-case maybe? The underlying bug seems similar to #573.

Does adding `/// cbindgen:ignore` to `pub type SplitSink` help? Also, maybe there's other similar typedefs that you're hitting instead?

Thanks

**Comment by FourLeafTec** [comment]
No help for add `/// cbindgen:ignore` to `pub type SplitSink`

I think i can create a test-case, but a few days later after my work fin.

**Comment by FourLeafTec** [comment]
I create a test case at [FourLeafTec/cbg_test_572](https://github.com/FourLeafTec/cbg_test_572)

**Comment by emilio** [comment]
That test-case is using cbindgen 0.9, which hadn't implemented the annotation. If I change the Cargo.toml to use 0.15 for example (latest release) it works just fine.
