### ISSUE TITLE
Can't generate bindings for a function containing lifetimes

### ISSUE THREAD

**Issue by Michael-F-Bryan** [eqrion/cbindgen#58]
I've got a function which returns an iterator over borrowed data, with a signature something like this:

```rust
pub struct ShapeIterator<'a>(Iter<'a, Object>);

pub unsafe extern "C" fn shape_iterator_new<'a>(objects: *mut Vec<Object>) -> *mut ShapeIterator<'a> {
  ...
}
```

Even though the `'a` litefime is essentially useless, I'm keeping it around because it reminds you the `ShapeIterator` is actually borrowed and the `Vec<Object>` needs to outlive it. 

It looks like including *any* lifetimes in a function's signature makes the crate think it contains generics, meaning the function is ignored. Would it be possible to relax this restriction?

**Comment by eqrion** [comment]
Yes, I think that's reasonable. I can't remember why I added that restriction in the first place...
