### ISSUE TITLE
Buildscript: Allow multiple crates

### ISSUE THREAD

**Issue by Kaiser1989** [eqrion/cbindgen#581]
Currently only one crate can be set in build script:

```
cbindgen::Builder::new()
    .with_crate(crate_dir)
    ...
```

As cargos dependencies allow to provide methods from dependend crates, it would be nice not only to add dependend types, but also all functions the dependend crate defines:

```
cbindgen::Builder::new()
    .with_crates(crate_dir, base_crate_dir)
    ...
```

This would result in a header file, providing all functions this library really has (with it's dependencies). 
Maybe i'm missing anything, but this doesn't seem to be possible by now.

**Comment by emilio** [comment]
I think the `extra_bindings` configuration option allows to do this, unless I'm missing something.

**Comment by Kaiser1989** [comment]
This seems to be available only in cbindgen.toml, not in buildscript

**Comment by emilio** [comment]
All the options with the build script are also available programatically fwiw.
