### ISSUE TITLE
0.14.4 and later versions of 0.14 broke semver

### ISSUE THREAD

**Issue by Xaeroxe** [eqrion/cbindgen#594]
0.14.4 introduced [`cbindgen::FunctionConfig::no_return`](https://docs.rs/cbindgen/0.14.4/cbindgen/struct.FunctionConfig.html#structfield.no_return) unfortunately this breaks code which manually builds the `FunctionConfig` structure because now a new member must be specified. Since 0.15 is out now, I'd recommend yanking 0.14.4, 0.14.5, and 0.14.6.

**Comment by emilio** [comment]
Indeed, you're right. 

Though generally I'd recommend using the following syntax:

```rust
FunctionConfig {
    foo: bar,
    ... Default::default(),
}
```

Which is a lot more future-proof. But you're right this is a breaking change technically. Is there a strong case for yanking the existing versions now that 0.15 is out?

**Comment by emilio** [comment]
Yanked those versions. Sorry for the trouble.
