### ISSUE TITLE
Allow specifying a profile for `cargo expand`

### ISSUE THREAD

**Issue by jrose-signal** [eqrion/cbindgen#603]
When `parse.expand` is enabled, cbindgen invokes Cargo to expand macros in the specified crates. If the dependencies of the crates in question have already been built, Cargo is smart enough to not build them from scratch. However, if the dependencies were only built in release mode, Cargo won't see them as valid build artifacts, and *will* rebuild everything (using the debug profile) just to do the expansion. If the `cargo` invocation in `cargo_expand.rs` allowed passing `--release`, this extra build could be avoided.

**Comment by emilio** [comment]
It seems we could automatically read the `PROFILE` env variable for this per https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts

Should be easy to write a patch, do you want to give it a shot?

**Comment by jrose-signal** [comment]
Sure, I'll see when I can grab some time.

…except, hm, this probably *isn't* a good idea when invoked within build.rs, because that already *can't* share artifacts with the main build. What do you think? (I really wish cbindgen could share the artifacts when invoked in build.rs, but there's probably no good way to get around the Cargo lockfile, huh.)

**Comment by emilio** [comment]
Hmm, that's a good point... Yeah, then probably a CLI option or such would be ok.

**Comment by emilio** [comment]
Fixed in https://github.com/eqrion/cbindgen/commit/0ba241498e4ceccf052ffa91883d53b7cdfb3a85.
