### ISSUE TITLE
Support splitting a field into multiple fields in a user-defined way

### ISSUE THREAD

**Issue by petrochenkov** [eqrion/cbindgen#608]
The title is a bit vague, so I'll give two use cases:

#### Use case 1: bitfields
```rust
struct S {
    /// cbindgen:???
    foo_and_bar: u64,
}
```
that should really turn into
```
struct S {
    uint8_t foo;
    uint64_t bar: 56;
};
```
, the Rust side doesn't uses bitfields just because Rust doesn't have them.

#### Use case 2: slices (#247)
```rust
struct S<'a> {
    /// cbindgen:???
    foos: &'a [Foo]
}
```
that should turn into
```rust
struct S {
    const Foo* foos;
    size_t foos_size;
};
```

@emilio 
I'm not sure at which abstraction level is this better solved.
- In the first case we should replace the Rust field at the generated text level, because Rust doesn't have bitfields to provide a conversion source (but perhaps we can come up with a syntax extension for bitfields usable inside `cbindgen` doc comments?).
- In the second case we'd want to perform the replacement at Rust level to keep the dependency on `Foo` because if `"const Foo* foos;\nsize_t foos_size;"` is substituted simply as a text, then the dependency on `Foo` will be lost.

(In this example the annotation is applied to fields, but the same idea of generic replacement is probably applicable to other entities as well.)

**Comment by petrochenkov** [comment]
One alternative solution to this that I can think of is supporting `/// cbindgen:ignore` on fields (https://github.com/eqrion/cbindgen/pull/579) AND supporting annotations like `/// cbindgen:bitfield=56` for generating bitfields.

Then the problems above would be solved by writing something like
```rust
struct S {
    /// cbindgen:ignore
    foo_and_bar: u64,
    #[cfg(feature = "cbindgen")]
    foo: u8,
    #[cfg(feature = "cbindgen")]
    /// cbindgen:bitfield=56
    bar: u64,
}

struct S<'a> {
    /// cbindgen:ignore
    foos: &'a [Foo]
    #[cfg(feature = "cbindgen")]
    foos: *const Foo,
    #[cfg(feature = "cbindgen")]
    foos_size: usize,
}
```

**Comment by emilio** [comment]
> Use case 1: bitfields

I don't think the two pieces of code you linked to are equivalent in MSVC / clang-cl. The equivalent thing would be:

```c
struct S {
    uint64_t foo: 8;
    uint64_t bar: 56;
};
```

That being said that doesn't invalidate the use-case.

> Use case 2: slices (#247)

Is their layout well-defined now? I know https://github.com/rust-lang/unsafe-code-guidelines/blob/master/reference/src/layout/pointers.md, but we've been hesitant on relying on that until a more "official" source was available.

If they're well-defined and reliable, I don't know why we should have annotations, we should just turn slices into a struct.

**Comment by petrochenkov** [comment]
Some update: supporting `/// cbindgen:ignore` on fields is not necessary, `cfg`ing things in and out with `feature = "cbindgen"` works good enough! cbindgen doesn't run compilation far enough to reach the missing field errors.

```
struct S {
    #[cfg(not(feature = "cbindgen"))]
    foo_and_bar: u64,
    #[cfg(feature = "cbindgen")]
    foo: u8,
    #[cfg(feature = "cbindgen")]
    /// cbindgen:bitfield=56
    bar: u64,
}

struct S<'a> {
    #[cfg(not(feature = "cbindgen"))]
    foos: &'a [Foo]
    #[cfg(feature = "cbindgen")]
    foos: *const Foo,
    #[cfg(feature = "cbindgen")]
    foos_size: usize,
}
```

**Comment by petrochenkov** [comment]
@emilio 
>Is their layout well-defined now?

With the `cfg`-based solution above it's not cbindgen who converts slices, so this is left under responsibility of the person who writes `cfg`s or annotations replacing slices with pointers and sizes.
(I'm personally sure enough in their stability to use them in my project, others may think different.)

**Comment by petrochenkov** [comment]
I'm going to close this issue since a solution for "splitting a field into multiple fields" was found, and open a new one for bitfield annotations.
