### ISSUE TITLE
Enums with #[repr(u64)] does not parse correctly

### ISSUE THREAD

**Issue by oddcoder** [eqrion/cbindgen#636]
consider the following example

```
#[repr(C, u64)]
pub enum ErrorMessage {
    FAIL = 0xFFFF_FFFF_FFFF_FFFF,
    PASS = 0x0,
}
```

ErrorMessage is converted into opaque `struct ErrorMessage` instead of enum in C.

**Comment by RReverser** [comment]
It's not an error, but why do you use `repr(C)` on this kind of enum? `repr(u64)` should be enough.

**Comment by oddcoder** [comment]
I thought `repr(C)` might help cbindgen in anyway, but it didn't I also tried without `repr(C)`

My goal is to get something like this

```
enum class ErrorMessage: uint64_t {
  FAIL = 0xFFFFFFFFFFFFFFFF,
  PASS = 0
};
```
But I am not able to get cbindgen to generate that, Also I meant to say C++ not C, that is a mistake on my end.

**Comment by emilio** [comment]
What doesn't work exactly? For this:

```rust
#[repr(C, u64)]
pub enum ErrorMessage {
    FAIL = 0xFFFF_FFFF_FFFF_FFFF,
    PASS = 0x0,
}

#[no_mangle]
pub extern "C" fn root(_: ErrorMessage) {}
```

Generates:

```c++
$ ./target/debug/cbindgen t.rs                                                                                                                                                                                                             
#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

enum class ErrorMessage : uint64_t {
  FAIL = 18446744073709551615ULL,
  PASS = 0,
};

extern "C" {

void root(ErrorMessage);

} // extern "C"
```

Which looks like the right code generation. Can you provide a complete test-case that doesn't work?

**Comment by oddcoder** [comment]
Sorry for the late response,

I tried little digging and found that It only works with cbindgen from master 

I tried the use binary cbindgen from crates.io

```rust
➜  ~ cat code.rs
#[repr(C, u64)]
pub enum ErrorMessage {
    FAIL = 0xFFFF_FFFF_FFFF_FFFF,
    PASS = 0x0,
}

#[no_mangle]
pub extern "C" fn root(_: ErrorMessage) {}
```
```C
➜  ~ cbindgen code.rs
#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

struct ErrorMessage;

extern "C" {

void root(ErrorMessage);

} // extern "C"

```
Still using cbindgen from master works as expected, will you  be able to push the current cbindgen to crates.io any time soon ?

**Comment by emilio** [comment]
Alright, b69a9cfe80b451ec32bc2b88e85d63195ed03e61 fixed this indeed.

Yeah, I'll do a release soon.

**Comment by emilio** [comment]
https://github.com/eqrion/cbindgen/releases/tag/v0.16.0
