### ISSUE TITLE
Types incompatible or not found using workspace featuring two crates

### ISSUE THREAD

**Issue by Nevsden** [eqrion/cbindgen#648]
Within my Rust workspace there are two crates: One which inhibits the source code and the other holds all bindings.
I want to automatically generate the `C` header file for all bindings. This requires `cbindgen` to look into the `core` crate and gather information of all the types that are not defined within the `bindings` crate. 
For every type, which should be found within the `core` crate however, `cbindgen` throws out a warning "incompatible type or not found". 

Now I am not sure, if my types are actually incompatible. However I know that for many types I defined, it has a header `#[repr(C)]` (which should atleast in theory give compatiblity to a c-type).

I also tried usind the `[extra_bindings]` keyword within cbindgen.toml however with no success. Any suggestions?

**Comment by Nevsden** [comment]
I added an examplatory project with the specifications of my issue:
https://github.com/Nevsden/rust_cbindgen_example_repo.git

When I run the cbindgen command on the workspace, the public struct `Point` cannot be found or is incompatible.

**Comment by emilio** [comment]
You need `parse_deps = true`.
