### ISSUE TITLE
Document the `documentation` option.

### ISSUE THREAD

**Issue by emilio** [eqrion/cbindgen#653]
We have an option to avoid generating documentation called, well, `documentation`.

Ironically, that option is undocumented, see [this comment](https://github.com/eqrion/cbindgen/pull/652#issuecomment-769782962).

We should add it to the template.toml and docs.md at least.

**Comment by Hywan** [comment]
Actually, there is [`Builder::with_documentation`](https://docs.rs/cbindgen/0.16.0/cbindgen/struct.Builder.html#method.with_documentation).

**Comment by emilio** [comment]
Right, but we should document that it is reachable from toml / etc as well.

**Comment by Hywan** [comment]
True!
