### ISSUE TITLE
user defined type in option is not expanded

### ISSUE THREAD

**Issue by tuxzz** [eqrion/cbindgen#660]
```
pub type FnPtr = fn() -> bool;

#[no_mangle]
pub extern "C" fn ffi_fn_1(f: Option<FnPtr>) {}

#[no_mangle]
pub extern "C" fn ffi_fn_2(f: Option<fn() -> bool>) {}
```

outputs
```
typedef struct Option_FnPtr Option_FnPtr;

void ffi_fn_1(Option_FnPtr f);
void ffi_fn_2(bool (*f)(void));
```

why `ffi_fn_1` is not same as `ffi_fn_2`?

**Comment by emilio** [comment]
This is a dupe of https://github.com/eqrion/cbindgen/issues/326. TLDR, it's a known bug, I'd totally take patches / help mentor to fix it, though I don't have the time myself to do it right now unless it matter for $dayjob :)
