### ISSUE TITLE
Conflicting typedefs with eg. glam

### ISSUE THREAD

**Issue by steadysupply** [eqrion/cbindgen#662]
I posted an issue over at https://github.com/bitshifter/glam-rs/issues/137 where cbindgen generates duplicate typedefs. The issue might be related to SSE types, since including `xmmintrin.h` reduced the number of compiler errors produced.

Are libraries like `glam` expected to be supported by cbindgen?

**Comment by steadysupply** [comment]
Types in `glam` do appear to use supported `repr` declarations (eg. their [`Vec3`](https://github.com/bitshifter/glam-rs/blob/9f8390783a0714e1f1db5efefcc4d82d77221530/src/vec3.rs#L267) type), but there might be other code that uses unsupported features.

**Comment by emilio** [comment]
So it seems that the different declarations come from different `#[cfg]` features. You should be able to make cbindgen `#ifdef` them as appropriate using the [relevant config options](https://github.com/eqrion/cbindgen/blob/master/docs.md#defines-and-cfgs).

Let me know if that doesn't work somehow.
