### ISSUE TITLE
Fails to parse `cast` crate

### ISSUE THREAD

**Issue by Manishearth** [eqrion/cbindgen#665]
I'm running cbindgen with `parse_deps = true` and it errors on 
https://github.com/japaric/cast.rs

```
$ cbindgen --config cbindgen.toml --crate cast --output foo.h
ERROR: Parsing crate `cast`:`/home/manishearth/dev/Git/cast.rs/src/lib.rs`:
Error("expected `:`")
Try running `rustc -Z parse-only /home/manishearth/dev/Git/cast.rs/src/lib.rs` to see a nicer error message
ERROR: Couldn't generate bindings for /home/manishearth/dev/Git/cast.rs.
```

**Comment by emilio** [comment]
What does the `rustc -Z parse-only` commend there say? Generally this is probably a syn issue. Does it work if you build with a newer `syn` version?

**Comment by Manishearth** [comment]
The command succeeds. I think it's just an out of date syn but haven't had a chance to try yet

**Comment by emilio** [comment]
So here's a reduced test-case:

```
trait Foo {
    fn bar(i32) -> i32;
}
```

This syntax used to be fine in rust 2015 but I think it is not in rust 2018?

Anyhow, seems like a syn bug.

**Comment by Manishearth** [comment]
syn issue at https://github.com/dtolnay/syn/issues/972. It seems to be intentional, I filed https://github.com/japaric/cast.rs/pull/25 to fix cast.rs

**Comment by emilio** [comment]
Ok, seems there's not much to do here on cbindgen's side.

**Comment by Manishearth** [comment]
This is also broken on the latest stable version of `clap`.

Could we perhaps have a flag that allows it to _ignore_ broken deps?
