### ISSUE TITLE
bool binding is incorrect for repr(C)

### ISSUE THREAD

**Issue by graphitemaster** [eqrion/cbindgen#670]
Rust has 1-byte size and alignment `bool`. This project maps `repr(C)` bool usage to C's `stdbool.h` header (being a fancy macro for C99's `_Bool` type). C (and C++) does not require that `_Bool` have 1-byte size and alignment. There are platforms where it has 4-byte size and alignment.

The relevant language in the C11 specification is listed here:
6.2.5 paragraph 2
> An object declared as type _Bool is large enough to store the values 0 and 1.

6.7.2.1 footnote 122
> While the number of bits in a _Bool object is **at least CHAR_BIT**, the width (number of sign and value bits) of a _Bool may be just 1 bit. 

It needs to be at least `sizeof(char)`, but it can be larger.

The same is true in C++ as well, citing C++14 specification here:
5.3.3 paragraph 1 [expr.sizeof]
> The sizeof operator yields the number of bytes in the object representation of its operand. The operand is either an expression, which is an unevaluated operand (Clause 5), or a parenthesized type-id. The sizeof operator shall not be applied to an expression that has function or incomplete type, to an enumeration type whose underlying type is not fixed before all its enumerators have been declared, to the parenthesized name of such types, or to a glvalue that designates a bit-field. sizeof(char), sizeof(signed char) and sizeof(unsigned char) are 1. **The result of sizeof applied to any other fundamental type (3.9.1) is implementation-defined. [ Note: in particular, sizeof(bool), sizeof(char16_t), sizeof(char32_t), and sizeof(wchar_t) are implementation-defined.75 -- end note ] [ Note: See 1.7 for the definition of byte and 3.9 for the definition of object representation. -- end note ]**

As an example, very old versions of MSVC on Windows for use 4-byte bool for both C and C++.

This is probably not a big deal as `bool` has 1-byte size and alignment almost everywhere, but it's something I've been personally affected by on game consoles in particular. As Rust begins to gain new targets and platforms this is something worth looking into. I would propose emitting a Rust specific boolean typedef that is an alias for `unsigned char`.

**Comment by RReverser** [comment]
@graphitemaster This is not correct. Rust specifically defined `bool` as compatible with `_Bool` back in https://github.com/rust-lang/rfcs/issues/992.

See https://rust-lang.github.io/unsafe-code-guidelines/layout/scalars.html for more details.

> Rust has 1-byte size and alignment bool. 

It just happens to have 1-byte size and alignment on platforms that Rust supports today.

**Comment by graphitemaster** [comment]
@RReverser Ah that's good to know, thanks. The conventional 1-byte size and alignment foot notes in the beginner Rust book are just out of date then.

**Comment by RReverser** [comment]
> The conventional 1-byte size and alignment foot notes in the beginner Rust book are just out of date then.

I think it's just a simplification for beginners, because it's true on all existing platforms.
