### ISSUE TITLE
Error("expected `:`") when parsing anonymous trait parameters

### ISSUE THREAD

**Issue by baumanj** [eqrion/cbindgen#681]
Rust 2018 removed support for [anonymous trait parameters](https://doc.rust-lang.org/edition-guide/rust-2018/trait-system/no-anon-params.html) like:
```rust
trait T {
    fn f(u8);
}
```
but there still exists plenty of 2015 code ([example](https://github.com/japaric/cast.rs/blob/74cec5dcf2014ecfe7cb05837b147cbb4f49024e/src/lib.rs#L165)) which contains them. This is reproducible with:
```
$ cbindgen <(echo 'trait T { fn f(u8); }')
```
whereas this succeeds:
```
$ cbindgen <(echo 'trait T { fn f(_: u8); }')
```

**Comment by emilio** [comment]
Known (and probably wontfix unfortunately) syn issue, see #665.
