### ISSUE TITLE
PhantomPinned should be ignored just like PhantomData<T> 

### ISSUE THREAD

**Issue by kkoning** [eqrion/cbindgen#694]
cbindgen already ignores any item of type `PhantomData`.  It should also ignore anything that's `PhantomPinned` for the same reason.  

This looks like it's just as simple as adding a one-liner in src/bindgen/ir/ty.rs at line 401 extending the predicate to include `PhantomPinned`.  Or, at least, that worked for me.  But perhaps it also should be added to some tests?

**Comment by emilio** [comment]
Yeah, that seems fine. I'd totally take that one-liner with at least a test tweaked (there aren't that many test that use `PhantomData` so just tweaking them to also use `PhantomPinned` seems good enough).

Thanks!
