### ISSUE TITLE
export.mangle remove_underscores not respected for enums

### ISSUE THREAD

**Issue by adamski** [eqrion/cbindgen#705]
Currently, setting `remove_underscores = false` in `[export.mangle]` does not remove underscores for enums.

In our case, with the following config

```
[export.mangle]

remove_underscores = true
rename_types = "PascalCase"
```

And an enum

```
pub enum ConnectionType {
    Usb,
    Serial,
}

```

cbindgen generates the following definition

```
typedef enum ConnectionType
{
    ConnectionType_Usb,
    ConnectionType_Serial,
} ConnectionType;

```

The expected result is:

```
typedef enum ConnectionType
{
    ConnectionTypeUsb,
    ConnectionTypeSerial,
} ConnectionType;

```

**Comment by emilio** [comment]
There are various hard-coded underscores that should probably get fixed in `src/bindgen/ir/enumeration.rs`.

**Comment by adamski** [comment]
Got it thanks for the tip. The main one looks like https://github.com/eqrion/cbindgen/blob/57add9c86083b492266c8511fba30fb7c37cce25/src/bindgen/ir/enumeration.rs#L537 
I'll get a PR together soon.
