### ISSUE TITLE
"Prefix all the things" option to avoid conflicts

### ISSUE THREAD

**Issue by hashmal** [eqrion/cbindgen#71]
When generating C++ it's possible to use namespaces, but I don't find an option to prefix all identifiers when generating plain C (the option exists for functions though.) A typical prefix would be the name of the crate.

Am I wrong and the option exists somewhere? Would it be a good addition?

**Comment by eqrion** [comment]
No you're right, there is no option for this today. I think it would be a good addition.

The biggest reason I haven't done this yet is that it requires not just prefixing all the types, but also prefixing all the references to the types. That being said, it shouldn't be too challenging.

**Comment by eqrion** [comment]
This was added in `0.4.0` as:
```toml
[export]
prefix = "CAPI_"
```
It can also be used with `Builder`. Feel free to reopen if this doesn't work for you.
