### ISSUE TITLE
hide type detail when using type alias?

### ISSUE THREAD

**Issue by myrfy001** [eqrion/cbindgen#711]
For the following rust code, with command `cbindgen --lang C t.rs`
```rust
type Context = HashMap<String, String>;

#[no_mangle]
pub extern fn new_context() -> *const Context{}
```
will generate the following C code:
```C
typedef struct HashMap_String__String HashMap_String__String;

typedef struct HashMap_String__String Context;

const Context *new_context(void);
```

I don't want to let the enduser know the detail of `Context` is a `HashMap_String__String`, they should only know it's a type of `Context`, how can I do that?

Thanks

**Comment by myrfy001** [comment]
It works! Thanks for the help~

**Comment by rlidwka** [comment]
> struct Context (HashMap<...>) should work?

Technically, newtypes are not guaranteed to have the same memory layout as their inner types, see https://github.com/rust-lang/rust/pull/87868#issuecomment-906471248.

I would want to put `repr(transparent)` on that Context so Rust compiler doesn't do anything funny. But adding it would make struct transparent to cbindgen as well.

@emilio is there a way to tell cbindgen to ignore `repr(transparent)` or `repr(C)` directives, and make the struct opaque instead? I was looking for something like `/// cbindgen:opaque` annotation, but nothing like this seem to exist at the moment.
