### ISSUE TITLE
repr in proc_macro

### ISSUE THREAD

**Issue by wzh19960613** [eqrion/cbindgen#728]
I wrote a repr attribute in a proc_macro, but it doesn't seem to work. Define just like this: 
```
#[proc_macro]
pub fn ffi_null_or(input: TokenStream) -> TokenStream {
    let str = input.to_string();
    let mut params = str.split(' ');
    let name = params.next().unwrap();
    let value_type = params.next().unwrap();
    let code = format!(
        r#"
            #[repr(u8)]
            pub enum {}OrNull {{
                Null,
                Value({})
            }}
        "#,
        name, value_type
    );
    code.parse().unwrap()
}
```
And use like this: 
```
ffi_null_or!(Int i64);
```
It can be compiled correctly, however the `bindings.h` generated by `cbindgen` dosen't contain the type named `IntOrNull`.

**Comment by emilio** [comment]
Yeah, this should work if you use the expand feature, but that's not enabled by default because it requires running cargo. Let me know if that doesn't work though.
