### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by xioTechnologies** [eqrion/cbindgen#731]
We are currently unable to publish the Rust API for our product because we require the fix introduced by [this commit](https://github.com/eqrion/cbindgen/commit/cbd4260bdc5c3ce50dd7ff14cb7c175e3f9544ad).  The author of the commit, @adamski is a member of our team.  Please can the next version including this commit be released as soon as possible.  Thank you.  @emilio

**Comment by adamski** [comment]
Hey @Emilio are you still around?

**Comment by emilio** [comment]
Err, yes, sorry... Been busy with other stuff and forgot to do this. On it.

**Comment by emilio** [comment]
https://github.com/eqrion/cbindgen/commit/b3de1dc4b438222ee8000afeeafdbe209adf337e, really sorry for the massive lag, I wish I had more bandwidth / be better at managing GitHub notifications :(
