### ISSUE TITLE
Failure to export constants defined by macros

### ISSUE THREAD

**Issue by catenacyber** [eqrion/cbindgen#735]
Following https://github.com/OISF/suricata/pull/6840#discussion_r790329352

Suricata rust crate has
`pub const PGSQL_LOG_PASSWORDS: u32 = BIT_U32!(1);`
And cbindgen fails to export this, running `cbindgen -v --config suricata/rust/cbindgen.toml --output suricata/rust/gen/rust-bindings.h` gives the following warning :

```
WARN: Skip suricata::PGSQL_LOG_PASSWORDS - (Unsupported expression. Macro(ExprMacro { attrs: [], mac: Macro { path: Path { leading_colon: None, segments: [PathSegment { ident: Ident(BIT_U32), arguments: None }] }, bang_token: Bang, delimiter: Paren(Paren), tokens: TokenStream [Literal { lit: 1 }] } }))
```

All works well if instead of using a macro, we use a constant such as `pub const PGSQL_LOG_PASSWORDS: u32 = 2;`

Would it be possible for cbindgen to support this ?

PS: for info, this macro is simply
```
macro_rules!BIT_U32 {
    ($x:expr) => (1 << $x);
}
```

**Comment by emilio** [comment]
We support this if you use the `cargo expand`, but otherwise macros can't really generally be supported. https://github.com/eqrion/cbindgen/issues/287 would allow something like this without cargo expand or so on. But yeah this is a known limitation.

**Comment by catenacyber** [comment]
Thanks for the suggestions, we will look into them...
