### ISSUE TITLE
How to include the struct defined in a different 3p crate in the c binding header files?

### ISSUE THREAD

**Issue by di-otter** [eqrion/cbindgen#737]
Given the scenario that I'm leveraging cbindgen (thks for the works^) in file A in crate A to generate c binding header file for file A. In this file A, Im using this struct `event` which is declared and defined in a different 3p crate B. How I can export this `event` struct in the final c binding header for file A? 

Currently cbindgen will simply attach this `event` struct in the header file but error throws when using the header file since the declaration and definition for `event` struct is missing. 

My current workaround to this problem is simply wrap around this struct with self-defined struct sorta like:
```
pub struct Event3pWrapper {
    event: Event
}
```

so that finally its only 
```
struct Event3pWrapper
```
show up in the header up and details are just encapsulated. 

any better way to do this? thks

**Comment by di-otter** [comment]
I also tried with the `type` e.g.
```
type EventFrom3p = Event;
```

and accordingly in the header file, it will just be:
```
usuing EventFrom3p = Event;
```

so fail again since Event is exposed in the header file directly without definitions to refer to

**Comment by emilio** [comment]
This is possible via `extra_bindings` field, let me know if that doesn't work.
