### ISSUE TITLE
`usize_is_size_t` documented but not valid

### ISSUE THREAD

**Issue by Stovent** [eqrion/cbindgen#753]
docs.md mentions the `usize_is_size_t` option, but trying to use it gives an error in v0.21.0.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Couldn't parse config file: unknown field `usize_is_size_t`, expected one of `prefix`, `postfix`, `must_use`, `args`, `rename_args`, `swift_name_macro`, `sort_by`, `no_return` for key `fn` at line 21 column 1."'
```

If this option has effectively been removed, is there a replacement for it ?

**Comment by petrochenkov** [comment]
It's a global option, but it looks like you are using it inside a `[fn]` block in your toml config.

**Comment by Stovent** [comment]
Indeed it works as a global option, thanks.
The issue is that this option is listed under the `[fn]` block inside docs.md, so I thought it was an `fn` option.
