### ISSUE TITLE
Support renaming of items from other crates

### ISSUE THREAD

**Issue by jechase** [eqrion/cbindgen#76]
This can currently be (kind of) accomplished by importing the item and then creating a type alias like so:
```rust
use some::path::Struct;
type MyStruct = Struct;
```

Unfortunately, this results in this C:
```C
typedef struct {
    ...
} Struct;
typedef Struct MyStruct;
```
which can pollute the global namespace if the imported struct has too-generic of a name, and rather than renaming the imported item, just outputs both it and the alias.

It seems like importing the struct like `use some::path::Struct as MyStruct` should have the effect of generating something like
```C
typedef struct {
   ...
} MyStruct;
```
but instead results in a "can't find MyStruct" error.

It would be nice if item renaming was possible in this manner, or some other mechanism for renaming specific items.

My use case is that I have something declared in another crate that's `#[repr(C)]` that I'd like to re-export from my library, but renamed to match my naming conventions.

**Comment by eqrion** [comment]
This was added in `0.4.0` as:
```toml
[export.rename]
"Old" = "New"
```
It can also be used with `Builder`. Feel free to reopen if this doesn't work for you.
