### ISSUE TITLE
0.24.2 causes firefox and thunderbird to fail

### ISSUE THREAD

**Issue by voncloft** [eqrion/cbindgen#769]
I reported this to mozilla but i figure i might as well post here too when compiling thunderbird and firefox with the new cbindgen i get the following error

error: redefinition of 'ROOT_CLIP_CHAIN'

tried with previous version of cbindgen and no issues

**Comment by emilio** [comment]
Yes, this is expected, and not a `cbindgen` bug. WebRender was defining that constant manually, and cbindgen is able to generate it now, removing it from `webrender_ffi.h` is ok.
