### ISSUE TITLE
`Bindings::write<F: Write>` consumes argument

### ISSUE THREAD

**Issue by berkowski** [eqrion/cbindgen#776]
I'm trying to use `cbindgen` to generate a bunch of c++ structures for use in JSON deserialization via [nlohmann/json](https://github.com/nlohmann/json).  I don't need (or really want) full binary interop as I'm not calling the rust library directly and all info is passed through strings.

I'd like therefore to manipulate the generated header file some before it's written.  Mostly I'm just replacing some opaque types with `std::string` for the initial parsing.

It seems like I could use a `std::io::BuffWriter` object with `Bindings::write`, then further manipulate the results before writing the header file to disk but `Bindings::write` consumes it's argument:

```rust
let buffer = std::io::BufWriter::new(Vec::new());
cbindgen::Builder::new()
    .generate().unwrap()
    .write(buffer);

// Can't then get the result here:
let bytes = buffer.into_inner();
```

I'd be happy to work on a PR to enable this unless there's a better way of going about things.

**Comment by emilio** [comment]
Seems reasonable to pass only a mut ref, feel free to send a PR :)

**Comment by js2xxx** [comment]
I think you can just use this:
```rust
let mut buffer = std::io::BufWriter::new(Vec::new());
cbindgen::Builder::new()
    .generate().unwrap()
    .write(&mut buffer);

let bytes = buffer.into_inner();
```
It's like Rust std auto implements `Write` on every mutable reference of type `T where T: Write`. For more try this in [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=58ae5a0b2fc8a9213e3d92614c0878d4).
