### ISSUE TITLE
Why do types like Vec not bring up warnings even though they don't work when binding?

### ISSUE THREAD

**Issue by RandomGamingDev** [eqrion/cbindgen#783]
Types like Vec and BTreeSet, for example, don't bring up warnings when generating the bindings even though they don't work. These types don't seem to exist in C, C++, or the libraries included with the binding (cstdarg, cstdint, cstdlib, ostream, and new), and for the part wrapped in `extern "C"`, neither templates, nor generics exist in C. 
Why doesn't this type of stuff bring up warnings, and, if it's supposed to work how do I get it working?

**Comment by emilio** [comment]
Because we treat them as known opaque types. You can then use them via pointers (e.g., a `Box<BTreeSet<..>>` is a legal return type. See the link on the other issue for the relevant code.

**Comment by RandomGamingDev** [comment]
Thanks for telling me, I'll pass by pointer instead
