### ISSUE TITLE
Array not generated when size determined by const function

### ISSUE THREAD

**Issue by greenfierydragon** [eqrion/cbindgen#786]
In the bindings I am writing I have rust code like this:

```rust
use ::core::mem::size_of;

// Foo is not C-layout
pub struct Foo {
    a: f32,
    b: usize, // etc.
}

#[repr(C)]
pub struct Bar {
    inner: [u8; size_of::<Foo>()];
}
```

where I then use a reference to `inner`  and use pointers to translate it into `other_crate::Foo`.  The problem here is that the definition of `Bar` becomes `typedef struct Bar Bar` - which prevents it being stack-allocable (which is why I'm not just using a `void *`) as it becomes opaque. In theory `Bar` should be C-layout as it is just bytes, and I have functions in rust which will manipulate `Bar` for the C, but as mentioned before, the definition of `Bar` does not generate.

**Comment by emilio** [comment]
Even if we evaluated const functions (which is non-trivial) what you're trying to do doesn't seem sound. Alignment of Foo and Bar is different.

**Comment by greenfierydragon** [comment]
Fair point, I guess I will use opaque pointers then. Thanks for you're time.
