### ISSUE TITLE
cbindgen not exporting items declared after macro expansion.

### ISSUE THREAD

**Issue by chyyran** [eqrion/cbindgen#802]
I'm building a library that is intended to be loaded dynamically with `dlopen`/`LoadLibrary` so I'd like to have autogenerated function pointer types as well.

I came up with the following macro
```rust
macro_rules! extern_fn {
    ($(#[$($attrss:tt)*])* fn $func_name:ident ($($arg_name:ident : $arg_ty:ty),*) $body:block) => {
        paste::paste! {
            pub type [<PFN_ $func_name>] = unsafe extern "C" fn($($arg_name: $arg_ty,)*) -> $crate::ctypes::error_t;
        }

        #[no_mangle]
        $(#[$($attrss)*])*
        fn $func_name($($arg_name: $arg_ty,)*) -> $crate::ctypes::error_t {
            let result: Result<(), $crate::error::Error> = try {
                $body
            };

            let Err(e) = result else {
                return $crate::error::Error::ok()
            };
            e.export()
        }
    }
}


extern_fn! {
    fn do_stuff(filename: *const c_char) {
        // do stuff
    }
}
```

This would normally export a `#[no_mangle]` function `do_stuff`, and a function pointer type `PFN_do_stuff`. `cbindgen` does not detect either of these declarations. I tried `expand` but it fails with an error or hands indefinitely when I tell it to expand the crate name.

**Comment by dariusc93** [comment]
Did you use `cargo-expand` to see how it looks when the macro is expanded? If youre using cbindgen in your `build.rs` you would need to use the latest commit since that would fix the issue with expanding there. If youre using the command cli you would need to expand there.

**Comment by fhennig** [comment]
You have to enable macro expansion for your crate in the `cbindgen.toml`:

```
[parse.expand]
# A list of crate names that should be run through `cargo expand` before
# parsing to expand any macros. Note that if a crate is named here, it
# will always be parsed, even if the blacklist/whitelist says it shouldn't be.
#
# default: []
crates = ["euclid"]
```
[docs](https://github.com/eqrion/cbindgen/blob/master/docs.md)

**Comment by chyyran** [comment]
The latest commit fixes this for me.
