### ISSUE TITLE
Usage of parse.expand fails when using stable Rust Toolchain

### ISSUE THREAD

**Issue by doxblek** [eqrion/cbindgen#812]
The `parse.expand` feature leverages the `-Zunpretty=expanded` flag of the Rust Compiler to expand macros and then evaluating the generated code.

This compiler flag can only be used in a nightly setup. While Rust allows to override the toolchain (e.g. `cargo +nightly …`), this is not possible when using the prebuilt cbindgen CLI tool (e.g. `cbindgen --config cbindgen.toml --output myheader.h`). Calling cbindgen in such way results in a cryptic error message.

Instead, a workaround is required: `rustup default nightly && cbindgen … && rustup default stable`.

This workaround should not be required, since cbindgen could leverage the Rust functionality to override the used toolchain for the current execution. Rustup even provides a flag (`--install`) to install the nightly toolchain if it is not yet installed.

**Comment by emilio** [comment]
This is expected, also `CARGO=$(rustup +nightly which cargo)` should do it.

We don't really want to use nightly without any opt-in from the user, IMHO.

**Comment by jcaden** [comment]
I've submitted a PR that I think solves the issue not forcing the user to have nightly installed https://github.com/eqrion/cbindgen/pull/818

**Comment by doxblek** [comment]
I would like either approach
