### ISSUE TITLE
Avoid monomorphisation for C++?

### ISSUE THREAD

**Issue by RReverser** [eqrion/cbindgen#85]
I assume I'm missing something obvious, but is it really necessary to run monomorphisation for C++ output instead of converting generics to `template`s?

Are there cases where output and/or layout would be different from such in Rust?

**Comment by eqrion** [comment]
To my knowledge there isn't a case where the output or layout would be different from Rust.

The problem was mostly that you cannot have templated structs in an `extern "C"` block in C++ (testing on g++ 7.2). You could define the templated structs outside of the `extern "C"` block, and now that I look into it, it seems like the `extern "C"` block is only required to be around the function definitions.

So yes, I think we could emit templated structs when in C++ mode. The monomorphisation code is still required for C mode though.

**Comment by RReverser** [comment]
> The monomorphisation code is still required for C mode though.

It can generate a macro though for "poor man's generics" (I did this on some projects). Basically idea is that you generate something like:

```c
#define List(T) struct { T *data; size_t length; }
typedef List(char) List_char;
typedef List(long) List_long;
```

and then use these as needed.

**Comment by eqrion** [comment]
Yes I think that would also work.

One case where this is tricky is generic types that contain generic types, such as:
```rust
#[repr(C)]
struct Container<T> {
  internal: *const T,
  length: c_int,
}

#[repr(C)]
struct List<T> {
  internal: Container<T>
}
```

We then need to use `##` to create the correct mangled name.

```c
#define Container(T) struct { T *internal; int length; }
typedef Container(float) Container_float;

#define List(T) struct { Container_ ## T internal; }
typedef List(float) List_float;
```

I don't have a preference between the current implementation and using macro's and/or templates. My three priorities are making the headers more usable, the headers more readable, and the implementation simpler.

I could see this making the implementation simpler and headers more readable, so I'd be open to it.

**Comment by RReverser** [comment]
> One case where this is tricky is generic types that contain generic types, such as

Hm, yeah, that's an interesting case to consider.

**Comment by fanzeyi** [comment]
Sadly MSVC does not like having template in FFI code. It will generate an error [C2526](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2526) for such usage.

```cpp
template<typename T>
class Wrapper<T>;

extern "C" Wrapper<int> foobar();
```

Godbolt: https://godbolt.org/z/Wj3-ZY

I don't have any good suggestions here, and I probably will work around this by manually defining the interface for related types :(

**Comment by RReverser** [comment]
@fanzeyi Not that it helps your case, but honestly, these days I'd probably just use Clang on Windows. It has a great support, and even Microsoft seems to be actively involved with its development.
