### ISSUE TITLE
rustfmt on code?

### ISSUE THREAD

**Issue by RReverser** [eqrion/cbindgen#86]
It would be nice if code would be formatted with [`rustfmt-nightly`](https://github.com/rust-lang-nursery/rustfmt) as currently it seems to contain custom ASCII-art-indentation which somewhat unnecessary raises complexity of contribution process.

**Comment by eqrion** [comment]
Certainly, I had some difficulty getting `rustfmt-nightly` working the first time I tried. I'll look into it again.

**Comment by eqrion** [comment]
I've been able to get `rustfmt-nightly` working properly now. I'll be happy to apply it to the tree once there are no large PR's in progress.

**Comment by RReverser** [comment]
PRs shouldn't be a problem anyway - I can just apply rustfmt on them too and then there will be no conflicts (the perks of autoformatting tools 😄 ).

**Comment by RReverser** [comment]
@eqrion Probably a good time now :)

**Comment by eqrion** [comment]
58d3178dc538af317cdfffe7de79e1420e1db293 formatted master with `rustfmt-nightly`.

I'd also like to run `cargo fmt -- --write-mode=diff` in travis, but I'm not quite sure how to only have it run when testing nightly as travis also tests stable and beta.
