### ISSUE TITLE
Structures not generated if not used by a function

### ISSUE THREAD

**Issue by klefevre** [eqrion/cbindgen#96]
If I have a `crate` with only structures defined in it without any `functions` using them. The parser will find them and take them (the logger output them correctly) but they won't be generated.

But if I add a dummy function using one of these structures (or any other type), then this structure and the dummy function would be generated correctly (ignoring all other that could be present).

Is there a way to tell cbindgen to generate every symbols even if there are not used directly ?

**Comment by eqrion** [comment]
There is currently no a way to do this. The logic being that emitting struct definitions without any functions from the rust library to use them with, wouldn't be useful. Is there a specific use case you need?

Regardless, I think it's a reasonable feature to add.

**Comment by klefevre** [comment]
Currently we have a crate that has a dependency  to 2 others crate that both define an ontology (only structs, enums and typealiases). And for reasons some of these symbols should be passed via an opaque pointer. That’s why they aren’t explicitly used in functions.

**Comment by eqrion** [comment]
This was added in `cbindgen` 0.4.0 as:
```toml
[export]
include = ["Foo"]
```
It can also be used with `Builder`. Feel free to reopen if it doesn't work for you.
